// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tools/teal/pulsar/ui/demoapp/schemas_tenant/v1/schemas_tenant.proto

package com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1;

/**
 * Protobuf enum {@code tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.CoffeeEnum}
 */
public enum CoffeeEnum
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>COFFEE_ENUM_UNSPECIFIED = 0;</code>
   */
  COFFEE_ENUM_UNSPECIFIED(0),
  /**
   * <code>COFFEE_ENUM_ESPRESSO = 1;</code>
   */
  COFFEE_ENUM_ESPRESSO(1),
  /**
   * <code>COFFEE_ENUM_AMERICANO = 2;</code>
   */
  COFFEE_ENUM_AMERICANO(2),
  /**
   * <code>COFFEE_ENUM_CAPPUCCINO = 3;</code>
   */
  COFFEE_ENUM_CAPPUCCINO(3),
  /**
   * <code>COFFEE_ENUM_FRAPPE = 4;</code>
   */
  COFFEE_ENUM_FRAPPE(4),
  /**
   * <code>COFFEE_ENUM_FLAT_WHITE = 5;</code>
   */
  COFFEE_ENUM_FLAT_WHITE(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>COFFEE_ENUM_UNSPECIFIED = 0;</code>
   */
  public static final int COFFEE_ENUM_UNSPECIFIED_VALUE = 0;
  /**
   * <code>COFFEE_ENUM_ESPRESSO = 1;</code>
   */
  public static final int COFFEE_ENUM_ESPRESSO_VALUE = 1;
  /**
   * <code>COFFEE_ENUM_AMERICANO = 2;</code>
   */
  public static final int COFFEE_ENUM_AMERICANO_VALUE = 2;
  /**
   * <code>COFFEE_ENUM_CAPPUCCINO = 3;</code>
   */
  public static final int COFFEE_ENUM_CAPPUCCINO_VALUE = 3;
  /**
   * <code>COFFEE_ENUM_FRAPPE = 4;</code>
   */
  public static final int COFFEE_ENUM_FRAPPE_VALUE = 4;
  /**
   * <code>COFFEE_ENUM_FLAT_WHITE = 5;</code>
   */
  public static final int COFFEE_ENUM_FLAT_WHITE_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CoffeeEnum valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static CoffeeEnum forNumber(int value) {
    switch (value) {
      case 0: return COFFEE_ENUM_UNSPECIFIED;
      case 1: return COFFEE_ENUM_ESPRESSO;
      case 2: return COFFEE_ENUM_AMERICANO;
      case 3: return COFFEE_ENUM_CAPPUCCINO;
      case 4: return COFFEE_ENUM_FRAPPE;
      case 5: return COFFEE_ENUM_FLAT_WHITE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CoffeeEnum>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CoffeeEnum> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CoffeeEnum>() {
          public CoffeeEnum findValueByNumber(int number) {
            return CoffeeEnum.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SchemasTenantProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final CoffeeEnum[] VALUES = values();

  public static CoffeeEnum valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CoffeeEnum(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.CoffeeEnum)
}

