// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tools/teal/pulsar/ui/demoapp/schemas_tenant/v1/schemas_tenant.proto

package com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1;

/**
 * Protobuf type {@code tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage}
 */
public final class ProtobufNativeDemoMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage)
    ProtobufNativeDemoMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProtobufNativeDemoMessage.newBuilder() to construct.
  private ProtobufNativeDemoMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProtobufNativeDemoMessage() {
    string_ = "";
    bytes_ = com.google.protobuf.ByteString.EMPTY;
    enum_ = 0;
    repeated_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProtobufNativeDemoMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SchemasTenantProto.internal_static_tools_teal_pulsar_ui_demoapp_schemas_tenant_v1_ProtobufNativeDemoMessage_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 18:
        return internalGetMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SchemasTenantProto.internal_static_tools_teal_pulsar_ui_demoapp_schemas_tenant_v1_ProtobufNativeDemoMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage.class, com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage.Builder.class);
  }

  private int oneofCase_ = 0;
  private java.lang.Object oneof_;
  public enum OneofCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    ONEOF_STRING(100),
    ONEOF_INT32(101),
    ONEOF_BOOL(102),
    ONEOF_NOT_SET(0);
    private final int value;
    private OneofCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OneofCase valueOf(int value) {
      return forNumber(value);
    }

    public static OneofCase forNumber(int value) {
      switch (value) {
        case 100: return ONEOF_STRING;
        case 101: return ONEOF_INT32;
        case 102: return ONEOF_BOOL;
        case 0: return ONEOF_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public OneofCase
  getOneofCase() {
    return OneofCase.forNumber(
        oneofCase_);
  }

  public static final int DOUBLE_FIELD_NUMBER = 1;
  private double double_;
  /**
   * <code>double double = 1 [json_name = "double"];</code>
   * @return The double.
   */
  @java.lang.Override
  public double getDouble() {
    return double_;
  }

  public static final int FLOAT_FIELD_NUMBER = 2;
  private float float_;
  /**
   * <code>float float = 2 [json_name = "float"];</code>
   * @return The float.
   */
  @java.lang.Override
  public float getFloat() {
    return float_;
  }

  public static final int INT32_FIELD_NUMBER = 3;
  private int int32_;
  /**
   * <code>int32 int32 = 3 [json_name = "int32"];</code>
   * @return The int32.
   */
  @java.lang.Override
  public int getInt32() {
    return int32_;
  }

  public static final int INT64_FIELD_NUMBER = 4;
  private long int64_;
  /**
   * <code>int64 int64 = 4 [json_name = "int64"];</code>
   * @return The int64.
   */
  @java.lang.Override
  public long getInt64() {
    return int64_;
  }

  public static final int UINT32_FIELD_NUMBER = 5;
  private int uint32_;
  /**
   * <code>uint32 uint32 = 5 [json_name = "uint32"];</code>
   * @return The uint32.
   */
  @java.lang.Override
  public int getUint32() {
    return uint32_;
  }

  public static final int UINT64_FIELD_NUMBER = 6;
  private long uint64_;
  /**
   * <code>uint64 uint64 = 6 [json_name = "uint64"];</code>
   * @return The uint64.
   */
  @java.lang.Override
  public long getUint64() {
    return uint64_;
  }

  public static final int SINT32_FIELD_NUMBER = 7;
  private int sint32_;
  /**
   * <code>sint32 sint32 = 7 [json_name = "sint32"];</code>
   * @return The sint32.
   */
  @java.lang.Override
  public int getSint32() {
    return sint32_;
  }

  public static final int SINT64_FIELD_NUMBER = 8;
  private long sint64_;
  /**
   * <code>sint64 sint64 = 8 [json_name = "sint64"];</code>
   * @return The sint64.
   */
  @java.lang.Override
  public long getSint64() {
    return sint64_;
  }

  public static final int FIXED32_FIELD_NUMBER = 9;
  private int fixed32_;
  /**
   * <code>fixed32 fixed32 = 9 [json_name = "fixed32"];</code>
   * @return The fixed32.
   */
  @java.lang.Override
  public int getFixed32() {
    return fixed32_;
  }

  public static final int FIXED64_FIELD_NUMBER = 10;
  private long fixed64_;
  /**
   * <code>fixed64 fixed64 = 10 [json_name = "fixed64"];</code>
   * @return The fixed64.
   */
  @java.lang.Override
  public long getFixed64() {
    return fixed64_;
  }

  public static final int SFIXED32_FIELD_NUMBER = 11;
  private int sfixed32_;
  /**
   * <code>sfixed32 sfixed32 = 11 [json_name = "sfixed32"];</code>
   * @return The sfixed32.
   */
  @java.lang.Override
  public int getSfixed32() {
    return sfixed32_;
  }

  public static final int SFIXED64_FIELD_NUMBER = 12;
  private long sfixed64_;
  /**
   * <code>sfixed64 sfixed64 = 12 [json_name = "sfixed64"];</code>
   * @return The sfixed64.
   */
  @java.lang.Override
  public long getSfixed64() {
    return sfixed64_;
  }

  public static final int BOOL_FIELD_NUMBER = 13;
  private boolean bool_;
  /**
   * <code>bool bool = 13 [json_name = "bool"];</code>
   * @return The bool.
   */
  @java.lang.Override
  public boolean getBool() {
    return bool_;
  }

  public static final int STRING_FIELD_NUMBER = 14;
  private volatile java.lang.Object string_;
  /**
   * <code>string string = 14 [json_name = "string"];</code>
   * @return The string.
   */
  @java.lang.Override
  public java.lang.String getString() {
    java.lang.Object ref = string_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      string_ = s;
      return s;
    }
  }
  /**
   * <code>string string = 14 [json_name = "string"];</code>
   * @return The bytes for string.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStringBytes() {
    java.lang.Object ref = string_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      string_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BYTES_FIELD_NUMBER = 15;
  private com.google.protobuf.ByteString bytes_;
  /**
   * <code>bytes bytes = 15 [json_name = "bytes"];</code>
   * @return The bytes.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBytes() {
    return bytes_;
  }

  public static final int ENUM_FIELD_NUMBER = 16;
  private int enum_;
  /**
   * <code>.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.CoffeeEnum enum = 16 [json_name = "enum"];</code>
   * @return The enum numeric value on the wire for enum.
   */
  @java.lang.Override public int getEnumValue() {
    return enum_;
  }
  /**
   * <code>.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.CoffeeEnum enum = 16 [json_name = "enum"];</code>
   * @return The enum.
   */
  @java.lang.Override public com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.CoffeeEnum getEnum() {
    @SuppressWarnings("deprecation")
    com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.CoffeeEnum result = com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.CoffeeEnum.valueOf(enum_);
    return result == null ? com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.CoffeeEnum.UNRECOGNIZED : result;
  }

  public static final int NESTED_MESSAGE_FIELD_NUMBER = 17;
  private com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage nestedMessage_;
  /**
   * <code>.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage nested_message = 17 [json_name = "nestedMessage"];</code>
   * @return Whether the nestedMessage field is set.
   */
  @java.lang.Override
  public boolean hasNestedMessage() {
    return nestedMessage_ != null;
  }
  /**
   * <code>.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage nested_message = 17 [json_name = "nestedMessage"];</code>
   * @return The nestedMessage.
   */
  @java.lang.Override
  public com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage getNestedMessage() {
    return nestedMessage_ == null ? com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage.getDefaultInstance() : nestedMessage_;
  }
  /**
   * <code>.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage nested_message = 17 [json_name = "nestedMessage"];</code>
   */
  @java.lang.Override
  public com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessageOrBuilder getNestedMessageOrBuilder() {
    return getNestedMessage();
  }

  public static final int MAP_FIELD_NUMBER = 18;
  private static final class MapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Long> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Long>newDefaultInstance(
                com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SchemasTenantProto.internal_static_tools_teal_pulsar_ui_demoapp_schemas_tenant_v1_ProtobufNativeDemoMessage_MapEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.INT64,
                0L);
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Long> map_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
  internalGetMap() {
    if (map_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MapDefaultEntryHolder.defaultEntry);
    }
    return map_;
  }

  public int getMapCount() {
    return internalGetMap().getMap().size();
  }
  /**
   * <code>map&lt;string, int64&gt; map = 18 [json_name = "map"];</code>
   */

  @java.lang.Override
  public boolean containsMap(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMapMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Long> getMap() {
    return getMapMap();
  }
  /**
   * <code>map&lt;string, int64&gt; map = 18 [json_name = "map"];</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.Long> getMapMap() {
    return internalGetMap().getMap();
  }
  /**
   * <code>map&lt;string, int64&gt; map = 18 [json_name = "map"];</code>
   */
  @java.lang.Override

  public long getMapOrDefault(
      java.lang.String key,
      long defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, int64&gt; map = 18 [json_name = "map"];</code>
   */
  @java.lang.Override

  public long getMapOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetMap().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int REPEATED_FIELD_NUMBER = 19;
  private com.google.protobuf.LazyStringList repeated_;
  /**
   * <code>repeated string repeated = 19 [json_name = "repeated"];</code>
   * @return A list containing the repeated.
   */
  public com.google.protobuf.ProtocolStringList
      getRepeatedList() {
    return repeated_;
  }
  /**
   * <code>repeated string repeated = 19 [json_name = "repeated"];</code>
   * @return The count of repeated.
   */
  public int getRepeatedCount() {
    return repeated_.size();
  }
  /**
   * <code>repeated string repeated = 19 [json_name = "repeated"];</code>
   * @param index The index of the element to return.
   * @return The repeated at the given index.
   */
  public java.lang.String getRepeated(int index) {
    return repeated_.get(index);
  }
  /**
   * <code>repeated string repeated = 19 [json_name = "repeated"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the repeated at the given index.
   */
  public com.google.protobuf.ByteString
      getRepeatedBytes(int index) {
    return repeated_.getByteString(index);
  }

  public static final int ONEOF_STRING_FIELD_NUMBER = 100;
  /**
   * <code>string oneof_string = 100 [json_name = "oneofString"];</code>
   * @return Whether the oneofString field is set.
   */
  public boolean hasOneofString() {
    return oneofCase_ == 100;
  }
  /**
   * <code>string oneof_string = 100 [json_name = "oneofString"];</code>
   * @return The oneofString.
   */
  public java.lang.String getOneofString() {
    java.lang.Object ref = "";
    if (oneofCase_ == 100) {
      ref = oneof_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (oneofCase_ == 100) {
        oneof_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string oneof_string = 100 [json_name = "oneofString"];</code>
   * @return The bytes for oneofString.
   */
  public com.google.protobuf.ByteString
      getOneofStringBytes() {
    java.lang.Object ref = "";
    if (oneofCase_ == 100) {
      ref = oneof_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (oneofCase_ == 100) {
        oneof_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ONEOF_INT32_FIELD_NUMBER = 101;
  /**
   * <code>int32 oneof_int32 = 101 [json_name = "oneofInt32"];</code>
   * @return Whether the oneofInt32 field is set.
   */
  @java.lang.Override
  public boolean hasOneofInt32() {
    return oneofCase_ == 101;
  }
  /**
   * <code>int32 oneof_int32 = 101 [json_name = "oneofInt32"];</code>
   * @return The oneofInt32.
   */
  @java.lang.Override
  public int getOneofInt32() {
    if (oneofCase_ == 101) {
      return (java.lang.Integer) oneof_;
    }
    return 0;
  }

  public static final int ONEOF_BOOL_FIELD_NUMBER = 102;
  /**
   * <code>bool oneof_bool = 102 [json_name = "oneofBool"];</code>
   * @return Whether the oneofBool field is set.
   */
  @java.lang.Override
  public boolean hasOneofBool() {
    return oneofCase_ == 102;
  }
  /**
   * <code>bool oneof_bool = 102 [json_name = "oneofBool"];</code>
   * @return The oneofBool.
   */
  @java.lang.Override
  public boolean getOneofBool() {
    if (oneofCase_ == 102) {
      return (java.lang.Boolean) oneof_;
    }
    return false;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Double.doubleToRawLongBits(double_) != 0) {
      output.writeDouble(1, double_);
    }
    if (java.lang.Float.floatToRawIntBits(float_) != 0) {
      output.writeFloat(2, float_);
    }
    if (int32_ != 0) {
      output.writeInt32(3, int32_);
    }
    if (int64_ != 0L) {
      output.writeInt64(4, int64_);
    }
    if (uint32_ != 0) {
      output.writeUInt32(5, uint32_);
    }
    if (uint64_ != 0L) {
      output.writeUInt64(6, uint64_);
    }
    if (sint32_ != 0) {
      output.writeSInt32(7, sint32_);
    }
    if (sint64_ != 0L) {
      output.writeSInt64(8, sint64_);
    }
    if (fixed32_ != 0) {
      output.writeFixed32(9, fixed32_);
    }
    if (fixed64_ != 0L) {
      output.writeFixed64(10, fixed64_);
    }
    if (sfixed32_ != 0) {
      output.writeSFixed32(11, sfixed32_);
    }
    if (sfixed64_ != 0L) {
      output.writeSFixed64(12, sfixed64_);
    }
    if (bool_ != false) {
      output.writeBool(13, bool_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(string_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, string_);
    }
    if (!bytes_.isEmpty()) {
      output.writeBytes(15, bytes_);
    }
    if (enum_ != com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.CoffeeEnum.COFFEE_ENUM_UNSPECIFIED.getNumber()) {
      output.writeEnum(16, enum_);
    }
    if (nestedMessage_ != null) {
      output.writeMessage(17, getNestedMessage());
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetMap(),
        MapDefaultEntryHolder.defaultEntry,
        18);
    for (int i = 0; i < repeated_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 19, repeated_.getRaw(i));
    }
    if (oneofCase_ == 100) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 100, oneof_);
    }
    if (oneofCase_ == 101) {
      output.writeInt32(
          101, (int)((java.lang.Integer) oneof_));
    }
    if (oneofCase_ == 102) {
      output.writeBool(
          102, (boolean)((java.lang.Boolean) oneof_));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(double_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, double_);
    }
    if (java.lang.Float.floatToRawIntBits(float_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, float_);
    }
    if (int32_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, int32_);
    }
    if (int64_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, int64_);
    }
    if (uint32_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, uint32_);
    }
    if (uint64_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, uint64_);
    }
    if (sint32_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(7, sint32_);
    }
    if (sint64_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt64Size(8, sint64_);
    }
    if (fixed32_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed32Size(9, fixed32_);
    }
    if (fixed64_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed64Size(10, fixed64_);
    }
    if (sfixed32_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSFixed32Size(11, sfixed32_);
    }
    if (sfixed64_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeSFixed64Size(12, sfixed64_);
    }
    if (bool_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(13, bool_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(string_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, string_);
    }
    if (!bytes_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(15, bytes_);
    }
    if (enum_ != com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.CoffeeEnum.COFFEE_ENUM_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(16, enum_);
    }
    if (nestedMessage_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(17, getNestedMessage());
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.Long> entry
         : internalGetMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
      map__ = MapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(18, map__);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < repeated_.size(); i++) {
        dataSize += computeStringSizeNoTag(repeated_.getRaw(i));
      }
      size += dataSize;
      size += 2 * getRepeatedList().size();
    }
    if (oneofCase_ == 100) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(100, oneof_);
    }
    if (oneofCase_ == 101) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(
            101, (int)((java.lang.Integer) oneof_));
    }
    if (oneofCase_ == 102) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            102, (boolean)((java.lang.Boolean) oneof_));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage)) {
      return super.equals(obj);
    }
    com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage other = (com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage) obj;

    if (java.lang.Double.doubleToLongBits(getDouble())
        != java.lang.Double.doubleToLongBits(
            other.getDouble())) return false;
    if (java.lang.Float.floatToIntBits(getFloat())
        != java.lang.Float.floatToIntBits(
            other.getFloat())) return false;
    if (getInt32()
        != other.getInt32()) return false;
    if (getInt64()
        != other.getInt64()) return false;
    if (getUint32()
        != other.getUint32()) return false;
    if (getUint64()
        != other.getUint64()) return false;
    if (getSint32()
        != other.getSint32()) return false;
    if (getSint64()
        != other.getSint64()) return false;
    if (getFixed32()
        != other.getFixed32()) return false;
    if (getFixed64()
        != other.getFixed64()) return false;
    if (getSfixed32()
        != other.getSfixed32()) return false;
    if (getSfixed64()
        != other.getSfixed64()) return false;
    if (getBool()
        != other.getBool()) return false;
    if (!getString()
        .equals(other.getString())) return false;
    if (!getBytes()
        .equals(other.getBytes())) return false;
    if (enum_ != other.enum_) return false;
    if (hasNestedMessage() != other.hasNestedMessage()) return false;
    if (hasNestedMessage()) {
      if (!getNestedMessage()
          .equals(other.getNestedMessage())) return false;
    }
    if (!internalGetMap().equals(
        other.internalGetMap())) return false;
    if (!getRepeatedList()
        .equals(other.getRepeatedList())) return false;
    if (!getOneofCase().equals(other.getOneofCase())) return false;
    switch (oneofCase_) {
      case 100:
        if (!getOneofString()
            .equals(other.getOneofString())) return false;
        break;
      case 101:
        if (getOneofInt32()
            != other.getOneofInt32()) return false;
        break;
      case 102:
        if (getOneofBool()
            != other.getOneofBool()) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DOUBLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getDouble()));
    hash = (37 * hash) + FLOAT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getFloat());
    hash = (37 * hash) + INT32_FIELD_NUMBER;
    hash = (53 * hash) + getInt32();
    hash = (37 * hash) + INT64_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getInt64());
    hash = (37 * hash) + UINT32_FIELD_NUMBER;
    hash = (53 * hash) + getUint32();
    hash = (37 * hash) + UINT64_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUint64());
    hash = (37 * hash) + SINT32_FIELD_NUMBER;
    hash = (53 * hash) + getSint32();
    hash = (37 * hash) + SINT64_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSint64());
    hash = (37 * hash) + FIXED32_FIELD_NUMBER;
    hash = (53 * hash) + getFixed32();
    hash = (37 * hash) + FIXED64_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFixed64());
    hash = (37 * hash) + SFIXED32_FIELD_NUMBER;
    hash = (53 * hash) + getSfixed32();
    hash = (37 * hash) + SFIXED64_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSfixed64());
    hash = (37 * hash) + BOOL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getBool());
    hash = (37 * hash) + STRING_FIELD_NUMBER;
    hash = (53 * hash) + getString().hashCode();
    hash = (37 * hash) + BYTES_FIELD_NUMBER;
    hash = (53 * hash) + getBytes().hashCode();
    hash = (37 * hash) + ENUM_FIELD_NUMBER;
    hash = (53 * hash) + enum_;
    if (hasNestedMessage()) {
      hash = (37 * hash) + NESTED_MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getNestedMessage().hashCode();
    }
    if (!internalGetMap().getMap().isEmpty()) {
      hash = (37 * hash) + MAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMap().hashCode();
    }
    if (getRepeatedCount() > 0) {
      hash = (37 * hash) + REPEATED_FIELD_NUMBER;
      hash = (53 * hash) + getRepeatedList().hashCode();
    }
    switch (oneofCase_) {
      case 100:
        hash = (37 * hash) + ONEOF_STRING_FIELD_NUMBER;
        hash = (53 * hash) + getOneofString().hashCode();
        break;
      case 101:
        hash = (37 * hash) + ONEOF_INT32_FIELD_NUMBER;
        hash = (53 * hash) + getOneofInt32();
        break;
      case 102:
        hash = (37 * hash) + ONEOF_BOOL_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getOneofBool());
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage)
      com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SchemasTenantProto.internal_static_tools_teal_pulsar_ui_demoapp_schemas_tenant_v1_ProtobufNativeDemoMessage_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 18:
          return internalGetMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 18:
          return internalGetMutableMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SchemasTenantProto.internal_static_tools_teal_pulsar_ui_demoapp_schemas_tenant_v1_ProtobufNativeDemoMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage.class, com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage.Builder.class);
    }

    // Construct using com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      double_ = 0D;

      float_ = 0F;

      int32_ = 0;

      int64_ = 0L;

      uint32_ = 0;

      uint64_ = 0L;

      sint32_ = 0;

      sint64_ = 0L;

      fixed32_ = 0;

      fixed64_ = 0L;

      sfixed32_ = 0;

      sfixed64_ = 0L;

      bool_ = false;

      string_ = "";

      bytes_ = com.google.protobuf.ByteString.EMPTY;

      enum_ = 0;

      if (nestedMessageBuilder_ == null) {
        nestedMessage_ = null;
      } else {
        nestedMessage_ = null;
        nestedMessageBuilder_ = null;
      }
      internalGetMutableMap().clear();
      repeated_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      oneofCase_ = 0;
      oneof_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SchemasTenantProto.internal_static_tools_teal_pulsar_ui_demoapp_schemas_tenant_v1_ProtobufNativeDemoMessage_descriptor;
    }

    @java.lang.Override
    public com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage getDefaultInstanceForType() {
      return com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage build() {
      com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage buildPartial() {
      com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage result = new com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage(this);
      int from_bitField0_ = bitField0_;
      result.double_ = double_;
      result.float_ = float_;
      result.int32_ = int32_;
      result.int64_ = int64_;
      result.uint32_ = uint32_;
      result.uint64_ = uint64_;
      result.sint32_ = sint32_;
      result.sint64_ = sint64_;
      result.fixed32_ = fixed32_;
      result.fixed64_ = fixed64_;
      result.sfixed32_ = sfixed32_;
      result.sfixed64_ = sfixed64_;
      result.bool_ = bool_;
      result.string_ = string_;
      result.bytes_ = bytes_;
      result.enum_ = enum_;
      if (nestedMessageBuilder_ == null) {
        result.nestedMessage_ = nestedMessage_;
      } else {
        result.nestedMessage_ = nestedMessageBuilder_.build();
      }
      result.map_ = internalGetMap();
      result.map_.makeImmutable();
      if (((bitField0_ & 0x00000002) != 0)) {
        repeated_ = repeated_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.repeated_ = repeated_;
      if (oneofCase_ == 100) {
        result.oneof_ = oneof_;
      }
      if (oneofCase_ == 101) {
        result.oneof_ = oneof_;
      }
      if (oneofCase_ == 102) {
        result.oneof_ = oneof_;
      }
      result.oneofCase_ = oneofCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage) {
        return mergeFrom((com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage other) {
      if (other == com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage.getDefaultInstance()) return this;
      if (other.getDouble() != 0D) {
        setDouble(other.getDouble());
      }
      if (other.getFloat() != 0F) {
        setFloat(other.getFloat());
      }
      if (other.getInt32() != 0) {
        setInt32(other.getInt32());
      }
      if (other.getInt64() != 0L) {
        setInt64(other.getInt64());
      }
      if (other.getUint32() != 0) {
        setUint32(other.getUint32());
      }
      if (other.getUint64() != 0L) {
        setUint64(other.getUint64());
      }
      if (other.getSint32() != 0) {
        setSint32(other.getSint32());
      }
      if (other.getSint64() != 0L) {
        setSint64(other.getSint64());
      }
      if (other.getFixed32() != 0) {
        setFixed32(other.getFixed32());
      }
      if (other.getFixed64() != 0L) {
        setFixed64(other.getFixed64());
      }
      if (other.getSfixed32() != 0) {
        setSfixed32(other.getSfixed32());
      }
      if (other.getSfixed64() != 0L) {
        setSfixed64(other.getSfixed64());
      }
      if (other.getBool() != false) {
        setBool(other.getBool());
      }
      if (!other.getString().isEmpty()) {
        string_ = other.string_;
        onChanged();
      }
      if (other.getBytes() != com.google.protobuf.ByteString.EMPTY) {
        setBytes(other.getBytes());
      }
      if (other.enum_ != 0) {
        setEnumValue(other.getEnumValue());
      }
      if (other.hasNestedMessage()) {
        mergeNestedMessage(other.getNestedMessage());
      }
      internalGetMutableMap().mergeFrom(
          other.internalGetMap());
      if (!other.repeated_.isEmpty()) {
        if (repeated_.isEmpty()) {
          repeated_ = other.repeated_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureRepeatedIsMutable();
          repeated_.addAll(other.repeated_);
        }
        onChanged();
      }
      switch (other.getOneofCase()) {
        case ONEOF_STRING: {
          oneofCase_ = 100;
          oneof_ = other.oneof_;
          onChanged();
          break;
        }
        case ONEOF_INT32: {
          setOneofInt32(other.getOneofInt32());
          break;
        }
        case ONEOF_BOOL: {
          setOneofBool(other.getOneofBool());
          break;
        }
        case ONEOF_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              double_ = input.readDouble();

              break;
            } // case 9
            case 21: {
              float_ = input.readFloat();

              break;
            } // case 21
            case 24: {
              int32_ = input.readInt32();

              break;
            } // case 24
            case 32: {
              int64_ = input.readInt64();

              break;
            } // case 32
            case 40: {
              uint32_ = input.readUInt32();

              break;
            } // case 40
            case 48: {
              uint64_ = input.readUInt64();

              break;
            } // case 48
            case 56: {
              sint32_ = input.readSInt32();

              break;
            } // case 56
            case 64: {
              sint64_ = input.readSInt64();

              break;
            } // case 64
            case 77: {
              fixed32_ = input.readFixed32();

              break;
            } // case 77
            case 81: {
              fixed64_ = input.readFixed64();

              break;
            } // case 81
            case 93: {
              sfixed32_ = input.readSFixed32();

              break;
            } // case 93
            case 97: {
              sfixed64_ = input.readSFixed64();

              break;
            } // case 97
            case 104: {
              bool_ = input.readBool();

              break;
            } // case 104
            case 114: {
              string_ = input.readStringRequireUtf8();

              break;
            } // case 114
            case 122: {
              bytes_ = input.readBytes();

              break;
            } // case 122
            case 128: {
              enum_ = input.readEnum();

              break;
            } // case 128
            case 138: {
              input.readMessage(
                  getNestedMessageFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 138
            case 146: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
              map__ = input.readMessage(
                  MapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableMap().getMutableMap().put(
                  map__.getKey(), map__.getValue());
              break;
            } // case 146
            case 154: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureRepeatedIsMutable();
              repeated_.add(s);
              break;
            } // case 154
            case 802: {
              java.lang.String s = input.readStringRequireUtf8();
              oneofCase_ = 100;
              oneof_ = s;
              break;
            } // case 802
            case 808: {
              oneof_ = input.readInt32();
              oneofCase_ = 101;
              break;
            } // case 808
            case 816: {
              oneof_ = input.readBool();
              oneofCase_ = 102;
              break;
            } // case 816
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int oneofCase_ = 0;
    private java.lang.Object oneof_;
    public OneofCase
        getOneofCase() {
      return OneofCase.forNumber(
          oneofCase_);
    }

    public Builder clearOneof() {
      oneofCase_ = 0;
      oneof_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private double double_ ;
    /**
     * <code>double double = 1 [json_name = "double"];</code>
     * @return The double.
     */
    @java.lang.Override
    public double getDouble() {
      return double_;
    }
    /**
     * <code>double double = 1 [json_name = "double"];</code>
     * @param value The double to set.
     * @return This builder for chaining.
     */
    public Builder setDouble(double value) {
      
      double_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double double = 1 [json_name = "double"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDouble() {
      
      double_ = 0D;
      onChanged();
      return this;
    }

    private float float_ ;
    /**
     * <code>float float = 2 [json_name = "float"];</code>
     * @return The float.
     */
    @java.lang.Override
    public float getFloat() {
      return float_;
    }
    /**
     * <code>float float = 2 [json_name = "float"];</code>
     * @param value The float to set.
     * @return This builder for chaining.
     */
    public Builder setFloat(float value) {
      
      float_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float float = 2 [json_name = "float"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFloat() {
      
      float_ = 0F;
      onChanged();
      return this;
    }

    private int int32_ ;
    /**
     * <code>int32 int32 = 3 [json_name = "int32"];</code>
     * @return The int32.
     */
    @java.lang.Override
    public int getInt32() {
      return int32_;
    }
    /**
     * <code>int32 int32 = 3 [json_name = "int32"];</code>
     * @param value The int32 to set.
     * @return This builder for chaining.
     */
    public Builder setInt32(int value) {
      
      int32_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 int32 = 3 [json_name = "int32"];</code>
     * @return This builder for chaining.
     */
    public Builder clearInt32() {
      
      int32_ = 0;
      onChanged();
      return this;
    }

    private long int64_ ;
    /**
     * <code>int64 int64 = 4 [json_name = "int64"];</code>
     * @return The int64.
     */
    @java.lang.Override
    public long getInt64() {
      return int64_;
    }
    /**
     * <code>int64 int64 = 4 [json_name = "int64"];</code>
     * @param value The int64 to set.
     * @return This builder for chaining.
     */
    public Builder setInt64(long value) {
      
      int64_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 int64 = 4 [json_name = "int64"];</code>
     * @return This builder for chaining.
     */
    public Builder clearInt64() {
      
      int64_ = 0L;
      onChanged();
      return this;
    }

    private int uint32_ ;
    /**
     * <code>uint32 uint32 = 5 [json_name = "uint32"];</code>
     * @return The uint32.
     */
    @java.lang.Override
    public int getUint32() {
      return uint32_;
    }
    /**
     * <code>uint32 uint32 = 5 [json_name = "uint32"];</code>
     * @param value The uint32 to set.
     * @return This builder for chaining.
     */
    public Builder setUint32(int value) {
      
      uint32_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 uint32 = 5 [json_name = "uint32"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUint32() {
      
      uint32_ = 0;
      onChanged();
      return this;
    }

    private long uint64_ ;
    /**
     * <code>uint64 uint64 = 6 [json_name = "uint64"];</code>
     * @return The uint64.
     */
    @java.lang.Override
    public long getUint64() {
      return uint64_;
    }
    /**
     * <code>uint64 uint64 = 6 [json_name = "uint64"];</code>
     * @param value The uint64 to set.
     * @return This builder for chaining.
     */
    public Builder setUint64(long value) {
      
      uint64_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 uint64 = 6 [json_name = "uint64"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUint64() {
      
      uint64_ = 0L;
      onChanged();
      return this;
    }

    private int sint32_ ;
    /**
     * <code>sint32 sint32 = 7 [json_name = "sint32"];</code>
     * @return The sint32.
     */
    @java.lang.Override
    public int getSint32() {
      return sint32_;
    }
    /**
     * <code>sint32 sint32 = 7 [json_name = "sint32"];</code>
     * @param value The sint32 to set.
     * @return This builder for chaining.
     */
    public Builder setSint32(int value) {
      
      sint32_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>sint32 sint32 = 7 [json_name = "sint32"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSint32() {
      
      sint32_ = 0;
      onChanged();
      return this;
    }

    private long sint64_ ;
    /**
     * <code>sint64 sint64 = 8 [json_name = "sint64"];</code>
     * @return The sint64.
     */
    @java.lang.Override
    public long getSint64() {
      return sint64_;
    }
    /**
     * <code>sint64 sint64 = 8 [json_name = "sint64"];</code>
     * @param value The sint64 to set.
     * @return This builder for chaining.
     */
    public Builder setSint64(long value) {
      
      sint64_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>sint64 sint64 = 8 [json_name = "sint64"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSint64() {
      
      sint64_ = 0L;
      onChanged();
      return this;
    }

    private int fixed32_ ;
    /**
     * <code>fixed32 fixed32 = 9 [json_name = "fixed32"];</code>
     * @return The fixed32.
     */
    @java.lang.Override
    public int getFixed32() {
      return fixed32_;
    }
    /**
     * <code>fixed32 fixed32 = 9 [json_name = "fixed32"];</code>
     * @param value The fixed32 to set.
     * @return This builder for chaining.
     */
    public Builder setFixed32(int value) {
      
      fixed32_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>fixed32 fixed32 = 9 [json_name = "fixed32"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFixed32() {
      
      fixed32_ = 0;
      onChanged();
      return this;
    }

    private long fixed64_ ;
    /**
     * <code>fixed64 fixed64 = 10 [json_name = "fixed64"];</code>
     * @return The fixed64.
     */
    @java.lang.Override
    public long getFixed64() {
      return fixed64_;
    }
    /**
     * <code>fixed64 fixed64 = 10 [json_name = "fixed64"];</code>
     * @param value The fixed64 to set.
     * @return This builder for chaining.
     */
    public Builder setFixed64(long value) {
      
      fixed64_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>fixed64 fixed64 = 10 [json_name = "fixed64"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFixed64() {
      
      fixed64_ = 0L;
      onChanged();
      return this;
    }

    private int sfixed32_ ;
    /**
     * <code>sfixed32 sfixed32 = 11 [json_name = "sfixed32"];</code>
     * @return The sfixed32.
     */
    @java.lang.Override
    public int getSfixed32() {
      return sfixed32_;
    }
    /**
     * <code>sfixed32 sfixed32 = 11 [json_name = "sfixed32"];</code>
     * @param value The sfixed32 to set.
     * @return This builder for chaining.
     */
    public Builder setSfixed32(int value) {
      
      sfixed32_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>sfixed32 sfixed32 = 11 [json_name = "sfixed32"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSfixed32() {
      
      sfixed32_ = 0;
      onChanged();
      return this;
    }

    private long sfixed64_ ;
    /**
     * <code>sfixed64 sfixed64 = 12 [json_name = "sfixed64"];</code>
     * @return The sfixed64.
     */
    @java.lang.Override
    public long getSfixed64() {
      return sfixed64_;
    }
    /**
     * <code>sfixed64 sfixed64 = 12 [json_name = "sfixed64"];</code>
     * @param value The sfixed64 to set.
     * @return This builder for chaining.
     */
    public Builder setSfixed64(long value) {
      
      sfixed64_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>sfixed64 sfixed64 = 12 [json_name = "sfixed64"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSfixed64() {
      
      sfixed64_ = 0L;
      onChanged();
      return this;
    }

    private boolean bool_ ;
    /**
     * <code>bool bool = 13 [json_name = "bool"];</code>
     * @return The bool.
     */
    @java.lang.Override
    public boolean getBool() {
      return bool_;
    }
    /**
     * <code>bool bool = 13 [json_name = "bool"];</code>
     * @param value The bool to set.
     * @return This builder for chaining.
     */
    public Builder setBool(boolean value) {
      
      bool_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool bool = 13 [json_name = "bool"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBool() {
      
      bool_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object string_ = "";
    /**
     * <code>string string = 14 [json_name = "string"];</code>
     * @return The string.
     */
    public java.lang.String getString() {
      java.lang.Object ref = string_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        string_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string string = 14 [json_name = "string"];</code>
     * @return The bytes for string.
     */
    public com.google.protobuf.ByteString
        getStringBytes() {
      java.lang.Object ref = string_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        string_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string string = 14 [json_name = "string"];</code>
     * @param value The string to set.
     * @return This builder for chaining.
     */
    public Builder setString(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      string_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string string = 14 [json_name = "string"];</code>
     * @return This builder for chaining.
     */
    public Builder clearString() {
      
      string_ = getDefaultInstance().getString();
      onChanged();
      return this;
    }
    /**
     * <code>string string = 14 [json_name = "string"];</code>
     * @param value The bytes for string to set.
     * @return This builder for chaining.
     */
    public Builder setStringBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      string_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString bytes_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes bytes = 15 [json_name = "bytes"];</code>
     * @return The bytes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBytes() {
      return bytes_;
    }
    /**
     * <code>bytes bytes = 15 [json_name = "bytes"];</code>
     * @param value The bytes to set.
     * @return This builder for chaining.
     */
    public Builder setBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bytes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes bytes = 15 [json_name = "bytes"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBytes() {
      
      bytes_ = getDefaultInstance().getBytes();
      onChanged();
      return this;
    }

    private int enum_ = 0;
    /**
     * <code>.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.CoffeeEnum enum = 16 [json_name = "enum"];</code>
     * @return The enum numeric value on the wire for enum.
     */
    @java.lang.Override public int getEnumValue() {
      return enum_;
    }
    /**
     * <code>.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.CoffeeEnum enum = 16 [json_name = "enum"];</code>
     * @param value The enum numeric value on the wire for enum to set.
     * @return This builder for chaining.
     */
    public Builder setEnumValue(int value) {
      
      enum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.CoffeeEnum enum = 16 [json_name = "enum"];</code>
     * @return The enum.
     */
    @java.lang.Override
    public com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.CoffeeEnum getEnum() {
      @SuppressWarnings("deprecation")
      com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.CoffeeEnum result = com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.CoffeeEnum.valueOf(enum_);
      return result == null ? com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.CoffeeEnum.UNRECOGNIZED : result;
    }
    /**
     * <code>.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.CoffeeEnum enum = 16 [json_name = "enum"];</code>
     * @param value The enum to set.
     * @return This builder for chaining.
     */
    public Builder setEnum(com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.CoffeeEnum value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      enum_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.CoffeeEnum enum = 16 [json_name = "enum"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEnum() {
      
      enum_ = 0;
      onChanged();
      return this;
    }

    private com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage nestedMessage_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage, com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage.Builder, com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessageOrBuilder> nestedMessageBuilder_;
    /**
     * <code>.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage nested_message = 17 [json_name = "nestedMessage"];</code>
     * @return Whether the nestedMessage field is set.
     */
    public boolean hasNestedMessage() {
      return nestedMessageBuilder_ != null || nestedMessage_ != null;
    }
    /**
     * <code>.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage nested_message = 17 [json_name = "nestedMessage"];</code>
     * @return The nestedMessage.
     */
    public com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage getNestedMessage() {
      if (nestedMessageBuilder_ == null) {
        return nestedMessage_ == null ? com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage.getDefaultInstance() : nestedMessage_;
      } else {
        return nestedMessageBuilder_.getMessage();
      }
    }
    /**
     * <code>.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage nested_message = 17 [json_name = "nestedMessage"];</code>
     */
    public Builder setNestedMessage(com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage value) {
      if (nestedMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        nestedMessage_ = value;
        onChanged();
      } else {
        nestedMessageBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage nested_message = 17 [json_name = "nestedMessage"];</code>
     */
    public Builder setNestedMessage(
        com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage.Builder builderForValue) {
      if (nestedMessageBuilder_ == null) {
        nestedMessage_ = builderForValue.build();
        onChanged();
      } else {
        nestedMessageBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage nested_message = 17 [json_name = "nestedMessage"];</code>
     */
    public Builder mergeNestedMessage(com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage value) {
      if (nestedMessageBuilder_ == null) {
        if (nestedMessage_ != null) {
          nestedMessage_ =
            com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage.newBuilder(nestedMessage_).mergeFrom(value).buildPartial();
        } else {
          nestedMessage_ = value;
        }
        onChanged();
      } else {
        nestedMessageBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage nested_message = 17 [json_name = "nestedMessage"];</code>
     */
    public Builder clearNestedMessage() {
      if (nestedMessageBuilder_ == null) {
        nestedMessage_ = null;
        onChanged();
      } else {
        nestedMessage_ = null;
        nestedMessageBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage nested_message = 17 [json_name = "nestedMessage"];</code>
     */
    public com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage.Builder getNestedMessageBuilder() {
      
      onChanged();
      return getNestedMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage nested_message = 17 [json_name = "nestedMessage"];</code>
     */
    public com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessageOrBuilder getNestedMessageOrBuilder() {
      if (nestedMessageBuilder_ != null) {
        return nestedMessageBuilder_.getMessageOrBuilder();
      } else {
        return nestedMessage_ == null ?
            com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage.getDefaultInstance() : nestedMessage_;
      }
    }
    /**
     * <code>.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage nested_message = 17 [json_name = "nestedMessage"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage, com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage.Builder, com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessageOrBuilder> 
        getNestedMessageFieldBuilder() {
      if (nestedMessageBuilder_ == null) {
        nestedMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage, com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage.Builder, com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessageOrBuilder>(
                getNestedMessage(),
                getParentForChildren(),
                isClean());
        nestedMessage_ = null;
      }
      return nestedMessageBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Long> map_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
    internalGetMap() {
      if (map_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MapDefaultEntryHolder.defaultEntry);
      }
      return map_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
    internalGetMutableMap() {
      onChanged();;
      if (map_ == null) {
        map_ = com.google.protobuf.MapField.newMapField(
            MapDefaultEntryHolder.defaultEntry);
      }
      if (!map_.isMutable()) {
        map_ = map_.copy();
      }
      return map_;
    }

    public int getMapCount() {
      return internalGetMap().getMap().size();
    }
    /**
     * <code>map&lt;string, int64&gt; map = 18 [json_name = "map"];</code>
     */

    @java.lang.Override
    public boolean containsMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long> getMap() {
      return getMapMap();
    }
    /**
     * <code>map&lt;string, int64&gt; map = 18 [json_name = "map"];</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.Long> getMapMap() {
      return internalGetMap().getMap();
    }
    /**
     * <code>map&lt;string, int64&gt; map = 18 [json_name = "map"];</code>
     */
    @java.lang.Override

    public long getMapOrDefault(
        java.lang.String key,
        long defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, int64&gt; map = 18 [json_name = "map"];</code>
     */
    @java.lang.Override

    public long getMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearMap() {
      internalGetMutableMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, int64&gt; map = 18 [json_name = "map"];</code>
     */

    public Builder removeMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long>
    getMutableMap() {
      return internalGetMutableMap().getMutableMap();
    }
    /**
     * <code>map&lt;string, int64&gt; map = 18 [json_name = "map"];</code>
     */
    public Builder putMap(
        java.lang.String key,
        long value) {
      if (key == null) { throw new NullPointerException("map key"); }
      
      internalGetMutableMap().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, int64&gt; map = 18 [json_name = "map"];</code>
     */

    public Builder putAllMap(
        java.util.Map<java.lang.String, java.lang.Long> values) {
      internalGetMutableMap().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.LazyStringList repeated_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureRepeatedIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        repeated_ = new com.google.protobuf.LazyStringArrayList(repeated_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string repeated = 19 [json_name = "repeated"];</code>
     * @return A list containing the repeated.
     */
    public com.google.protobuf.ProtocolStringList
        getRepeatedList() {
      return repeated_.getUnmodifiableView();
    }
    /**
     * <code>repeated string repeated = 19 [json_name = "repeated"];</code>
     * @return The count of repeated.
     */
    public int getRepeatedCount() {
      return repeated_.size();
    }
    /**
     * <code>repeated string repeated = 19 [json_name = "repeated"];</code>
     * @param index The index of the element to return.
     * @return The repeated at the given index.
     */
    public java.lang.String getRepeated(int index) {
      return repeated_.get(index);
    }
    /**
     * <code>repeated string repeated = 19 [json_name = "repeated"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the repeated at the given index.
     */
    public com.google.protobuf.ByteString
        getRepeatedBytes(int index) {
      return repeated_.getByteString(index);
    }
    /**
     * <code>repeated string repeated = 19 [json_name = "repeated"];</code>
     * @param index The index to set the value at.
     * @param value The repeated to set.
     * @return This builder for chaining.
     */
    public Builder setRepeated(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRepeatedIsMutable();
      repeated_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string repeated = 19 [json_name = "repeated"];</code>
     * @param value The repeated to add.
     * @return This builder for chaining.
     */
    public Builder addRepeated(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRepeatedIsMutable();
      repeated_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string repeated = 19 [json_name = "repeated"];</code>
     * @param values The repeated to add.
     * @return This builder for chaining.
     */
    public Builder addAllRepeated(
        java.lang.Iterable<java.lang.String> values) {
      ensureRepeatedIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, repeated_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string repeated = 19 [json_name = "repeated"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRepeated() {
      repeated_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string repeated = 19 [json_name = "repeated"];</code>
     * @param value The bytes of the repeated to add.
     * @return This builder for chaining.
     */
    public Builder addRepeatedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureRepeatedIsMutable();
      repeated_.add(value);
      onChanged();
      return this;
    }

    /**
     * <code>string oneof_string = 100 [json_name = "oneofString"];</code>
     * @return Whether the oneofString field is set.
     */
    @java.lang.Override
    public boolean hasOneofString() {
      return oneofCase_ == 100;
    }
    /**
     * <code>string oneof_string = 100 [json_name = "oneofString"];</code>
     * @return The oneofString.
     */
    @java.lang.Override
    public java.lang.String getOneofString() {
      java.lang.Object ref = "";
      if (oneofCase_ == 100) {
        ref = oneof_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (oneofCase_ == 100) {
          oneof_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string oneof_string = 100 [json_name = "oneofString"];</code>
     * @return The bytes for oneofString.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOneofStringBytes() {
      java.lang.Object ref = "";
      if (oneofCase_ == 100) {
        ref = oneof_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (oneofCase_ == 100) {
          oneof_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string oneof_string = 100 [json_name = "oneofString"];</code>
     * @param value The oneofString to set.
     * @return This builder for chaining.
     */
    public Builder setOneofString(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  oneofCase_ = 100;
      oneof_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string oneof_string = 100 [json_name = "oneofString"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOneofString() {
      if (oneofCase_ == 100) {
        oneofCase_ = 0;
        oneof_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string oneof_string = 100 [json_name = "oneofString"];</code>
     * @param value The bytes for oneofString to set.
     * @return This builder for chaining.
     */
    public Builder setOneofStringBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      oneofCase_ = 100;
      oneof_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>int32 oneof_int32 = 101 [json_name = "oneofInt32"];</code>
     * @return Whether the oneofInt32 field is set.
     */
    public boolean hasOneofInt32() {
      return oneofCase_ == 101;
    }
    /**
     * <code>int32 oneof_int32 = 101 [json_name = "oneofInt32"];</code>
     * @return The oneofInt32.
     */
    public int getOneofInt32() {
      if (oneofCase_ == 101) {
        return (java.lang.Integer) oneof_;
      }
      return 0;
    }
    /**
     * <code>int32 oneof_int32 = 101 [json_name = "oneofInt32"];</code>
     * @param value The oneofInt32 to set.
     * @return This builder for chaining.
     */
    public Builder setOneofInt32(int value) {
      oneofCase_ = 101;
      oneof_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 oneof_int32 = 101 [json_name = "oneofInt32"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOneofInt32() {
      if (oneofCase_ == 101) {
        oneofCase_ = 0;
        oneof_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>bool oneof_bool = 102 [json_name = "oneofBool"];</code>
     * @return Whether the oneofBool field is set.
     */
    public boolean hasOneofBool() {
      return oneofCase_ == 102;
    }
    /**
     * <code>bool oneof_bool = 102 [json_name = "oneofBool"];</code>
     * @return The oneofBool.
     */
    public boolean getOneofBool() {
      if (oneofCase_ == 102) {
        return (java.lang.Boolean) oneof_;
      }
      return false;
    }
    /**
     * <code>bool oneof_bool = 102 [json_name = "oneofBool"];</code>
     * @param value The oneofBool to set.
     * @return This builder for chaining.
     */
    public Builder setOneofBool(boolean value) {
      oneofCase_ = 102;
      oneof_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool oneof_bool = 102 [json_name = "oneofBool"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOneofBool() {
      if (oneofCase_ == 102) {
        oneofCase_ = 0;
        oneof_ = null;
        onChanged();
      }
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage)
  }

  // @@protoc_insertion_point(class_scope:tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage)
  private static final com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage();
  }

  public static com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProtobufNativeDemoMessage>
      PARSER = new com.google.protobuf.AbstractParser<ProtobufNativeDemoMessage>() {
    @java.lang.Override
    public ProtobufNativeDemoMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ProtobufNativeDemoMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtobufNativeDemoMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

