// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tools/teal/pulsar/ui/demoapp/schemas_tenant/v1/schemas_tenant.proto

package com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1;

public interface SimpleMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 x = 1 [json_name = "x"];</code>
   * @return The x.
   */
  int getX();

  /**
   * <code>int32 y = 2 [json_name = "y"];</code>
   * @return The y.
   */
  int getY();
}
