brokerServiceUrl: "pulsar://localhost:6650"
webServiceUrl: "http://localhost:8080"

loadConfig:
  enableNonPersistentTopics: false
  producerLoadMultiplier:
    overloaded: 1
    heavilyLoaded: 1
    moderatelyLoaded: 1
    lightlyLoaded: 1
  subscriptionAmount:
    overloaded: 1
    heavilyLoaded: 1
    moderatelyLoaded: 1
    lightlyLoaded: 1
  workersAmount: 10
