brokerServiceUrl: "pulsar+ssl://cluster-d.o-xy6ek.snio.cloud:6651"
webServiceUrl: "https://cluster-d.o-xy6ek.snio.cloud"
#brokerServiceUrl: "pulsar://localhost:6650"
#webServiceUrl: "http://localhost:8080"
#brokerServiceUrl: "pulsar+ssl://test2.o-xy6ek.snio.cloud:6651"
#webServiceUrl: "https://test2.o-xy6ek.snio.cloud"
auth:
  oauth2:
    issuerUrl: "https://auth.streamnative.cloud/"
    audience: "urn:sn:pulsar:o-xy6ek:instance-d"
    privateKey: "file:///home/alex/o-xy6ek-cluster-b-admin.json"
