// source: api/v1/topic.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.api.v1.Message');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Map');
goog.require('jspb.Message');
goog.require('proto.google.protobuf.Timestamp');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.v1.Message = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.v1.Message, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.v1.Message.displayName = 'proto.api.v1.Message';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.v1.Message.prototype.toObject = function(opt_includeInstance) {
  return proto.api.v1.Message.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.v1.Message} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1.Message.toObject = function(includeInstance, msg) {
  var f, obj = {
    propertiesMap: (f = msg.getPropertiesMap()) ? f.toObject(includeInstance, undefined) : [],
    data: msg.getData_asB64(),
    size: jspb.Message.getFieldWithDefault(msg, 3, 0),
    value: jspb.Message.getFieldWithDefault(msg, 4, ""),
    publishTime: (f = msg.getPublishTime()) && proto.google.protobuf.Timestamp.toObject(includeInstance, f),
    eventTime: (f = msg.getEventTime()) && proto.google.protobuf.Timestamp.toObject(includeInstance, f),
    brokerPublishTime: jspb.Message.getFloatingPointFieldWithDefault(msg, 22, 0.0),
    sequenceId: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
    producerName: jspb.Message.getFieldWithDefault(msg, 9, ""),
    key: jspb.Message.getFieldWithDefault(msg, 10, ""),
    orderingKey: jspb.Message.getFieldWithDefault(msg, 11, ""),
    topic: jspb.Message.getFieldWithDefault(msg, 12, ""),
    redeliveryCount: jspb.Message.getFieldWithDefault(msg, 13, 0),
    schemaVersion: msg.getSchemaVersion_asB64(),
    isReplicated: jspb.Message.getBooleanFieldWithDefault(msg, 20, false),
    replicatedFrom: jspb.Message.getFieldWithDefault(msg, 21, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.v1.Message}
 */
proto.api.v1.Message.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.v1.Message;
  return proto.api.v1.Message.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.v1.Message} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.v1.Message}
 */
proto.api.v1.Message.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = msg.getPropertiesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setData(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSize(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    case 6:
      var value = new proto.google.protobuf.Timestamp;
      reader.readMessage(value,proto.google.protobuf.Timestamp.deserializeBinaryFromReader);
      msg.setPublishTime(value);
      break;
    case 7:
      var value = new proto.google.protobuf.Timestamp;
      reader.readMessage(value,proto.google.protobuf.Timestamp.deserializeBinaryFromReader);
      msg.setEventTime(value);
      break;
    case 22:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setBrokerPublishTime(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setSequenceId(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setProducerName(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrderingKey(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setTopic(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRedeliveryCount(value);
      break;
    case 14:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSchemaVersion(value);
      break;
    case 20:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsReplicated(value);
      break;
    case 21:
      var value = /** @type {string} */ (reader.readString());
      msg.setReplicatedFrom(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.v1.Message.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.v1.Message.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.v1.Message} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1.Message.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPropertiesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(1, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getData_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getSize();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getValue();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getPublishTime();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.google.protobuf.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getEventTime();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.google.protobuf.Timestamp.serializeBinaryToWriter
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 22));
  if (f != null) {
    writer.writeDouble(
      22,
      f
    );
  }
  f = message.getSequenceId();
  if (f !== 0.0) {
    writer.writeDouble(
      8,
      f
    );
  }
  f = message.getProducerName();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getOrderingKey();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getTopic();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getRedeliveryCount();
  if (f !== 0) {
    writer.writeInt32(
      13,
      f
    );
  }
  f = message.getSchemaVersion_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      14,
      f
    );
  }
  f = message.getIsReplicated();
  if (f) {
    writer.writeBool(
      20,
      f
    );
  }
  f = message.getReplicatedFrom();
  if (f.length > 0) {
    writer.writeString(
      21,
      f
    );
  }
};


/**
 * map<string, string> properties = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.api.v1.Message.prototype.getPropertiesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 1, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.api.v1.Message} returns this
 */
proto.api.v1.Message.prototype.clearPropertiesMap = function() {
  this.getPropertiesMap().clear();
  return this;};


/**
 * optional bytes data = 2;
 * @return {string}
 */
proto.api.v1.Message.prototype.getData = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes data = 2;
 * This is a type-conversion wrapper around `getData()`
 * @return {string}
 */
proto.api.v1.Message.prototype.getData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getData()));
};


/**
 * optional bytes data = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getData()`
 * @return {!Uint8Array}
 */
proto.api.v1.Message.prototype.getData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getData()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.api.v1.Message} returns this
 */
proto.api.v1.Message.prototype.setData = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional int64 size = 3;
 * @return {number}
 */
proto.api.v1.Message.prototype.getSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.api.v1.Message} returns this
 */
proto.api.v1.Message.prototype.setSize = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string value = 4;
 * @return {string}
 */
proto.api.v1.Message.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.v1.Message} returns this
 */
proto.api.v1.Message.prototype.setValue = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional google.protobuf.Timestamp publish_time = 6;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.api.v1.Message.prototype.getPublishTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.Timestamp, 6));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.api.v1.Message} returns this
*/
proto.api.v1.Message.prototype.setPublishTime = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.v1.Message} returns this
 */
proto.api.v1.Message.prototype.clearPublishTime = function() {
  return this.setPublishTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.v1.Message.prototype.hasPublishTime = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.Timestamp event_time = 7;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.api.v1.Message.prototype.getEventTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.Timestamp, 7));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.api.v1.Message} returns this
*/
proto.api.v1.Message.prototype.setEventTime = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.v1.Message} returns this
 */
proto.api.v1.Message.prototype.clearEventTime = function() {
  return this.setEventTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.v1.Message.prototype.hasEventTime = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional double broker_publish_time = 22;
 * @return {number}
 */
proto.api.v1.Message.prototype.getBrokerPublishTime = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 22, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.api.v1.Message} returns this
 */
proto.api.v1.Message.prototype.setBrokerPublishTime = function(value) {
  return jspb.Message.setField(this, 22, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.api.v1.Message} returns this
 */
proto.api.v1.Message.prototype.clearBrokerPublishTime = function() {
  return jspb.Message.setField(this, 22, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.v1.Message.prototype.hasBrokerPublishTime = function() {
  return jspb.Message.getField(this, 22) != null;
};


/**
 * optional double sequence_id = 8;
 * @return {number}
 */
proto.api.v1.Message.prototype.getSequenceId = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.api.v1.Message} returns this
 */
proto.api.v1.Message.prototype.setSequenceId = function(value) {
  return jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional string producer_name = 9;
 * @return {string}
 */
proto.api.v1.Message.prototype.getProducerName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.v1.Message} returns this
 */
proto.api.v1.Message.prototype.setProducerName = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string key = 10;
 * @return {string}
 */
proto.api.v1.Message.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.v1.Message} returns this
 */
proto.api.v1.Message.prototype.setKey = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string ordering_key = 11;
 * @return {string}
 */
proto.api.v1.Message.prototype.getOrderingKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.v1.Message} returns this
 */
proto.api.v1.Message.prototype.setOrderingKey = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string topic = 12;
 * @return {string}
 */
proto.api.v1.Message.prototype.getTopic = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.v1.Message} returns this
 */
proto.api.v1.Message.prototype.setTopic = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional int32 redelivery_count = 13;
 * @return {number}
 */
proto.api.v1.Message.prototype.getRedeliveryCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.api.v1.Message} returns this
 */
proto.api.v1.Message.prototype.setRedeliveryCount = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * optional bytes schema_version = 14;
 * @return {string}
 */
proto.api.v1.Message.prototype.getSchemaVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * optional bytes schema_version = 14;
 * This is a type-conversion wrapper around `getSchemaVersion()`
 * @return {string}
 */
proto.api.v1.Message.prototype.getSchemaVersion_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSchemaVersion()));
};


/**
 * optional bytes schema_version = 14;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSchemaVersion()`
 * @return {!Uint8Array}
 */
proto.api.v1.Message.prototype.getSchemaVersion_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSchemaVersion()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.api.v1.Message} returns this
 */
proto.api.v1.Message.prototype.setSchemaVersion = function(value) {
  return jspb.Message.setProto3BytesField(this, 14, value);
};


/**
 * optional bool is_replicated = 20;
 * @return {boolean}
 */
proto.api.v1.Message.prototype.getIsReplicated = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 20, false));
};


/**
 * @param {boolean} value
 * @return {!proto.api.v1.Message} returns this
 */
proto.api.v1.Message.prototype.setIsReplicated = function(value) {
  return jspb.Message.setProto3BooleanField(this, 20, value);
};


/**
 * optional string replicated_from = 21;
 * @return {string}
 */
proto.api.v1.Message.prototype.getReplicatedFrom = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 21, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.v1.Message} returns this
 */
proto.api.v1.Message.prototype.setReplicatedFrom = function(value) {
  return jspb.Message.setProto3StringField(this, 21, value);
};


