import { IoConfigField } from "../../../../IoConfigField/IoConfigField"

export type RabbitMQConfigs = {
  [key: string]: string | number
  connectionName: string,
  host: string,
  port: number,
  virtualHost: string,
  username: string,
  password: string,
  queueName: string,
  requestedChannelMax: number,
  requestedFrameMax: number,
  connectionTimeout: number,
  handshakeTimeout: number,
  requestedHeartbeat: number,
  exchangeName: string,
  routingKey: string,
}

export const rabbitMQFields: IoConfigField[] = [
  {
    name: 'connectionName',
    type: 'string',
    isRequired: true,
    help: 'help',
    label: 'Connection name',
  },
  {
    name: 'host',
    type: 'string',
    isRequired: true,
    help: 'help',
    label: 'Host',
  },
  {
    name: 'port',
    type: 'int',
    isRequired: true,
    help: 'help',
    label: 'Port',
  },
  {
    name: 'virtualHost',
    type: 'string',
    isRequired: true,
    help: 'help',
    label: 'Virtual host',
  },
  {
    name: 'username',
    type: 'string',
    isRequired: false,
    help: 'help',
    label: 'Username',
  },
  {
    name: 'password',
    type: 'string',
    isRequired: false,
    help: 'help',
    label: 'Password',
  },
  {
    name: 'queueName',
    type: 'string',
    isRequired: true,
    help: 'help',
    label: 'Queue name',
  },
  {
    name: 'requestedChannelMax',
    type: 'int',
    isRequired: false,
    help: 'help',
    label: 'Requested channel max',
  },
  {
    name: 'requestedFrameMax',
    type: 'int',
    isRequired: false,
    help: 'help',
    label: 'Requested frame max',
  },
  {
    name: 'connectionTimeout',
    type: 'duration',
    isRequired: false,
    help: 'help',
    label: 'Connection timeout',
  },
  {
    name: 'handshakeTimeout',
    type: 'duration',
    isRequired: false,
    help: 'help',
    label: 'Handshake timeout',
  },
  {
    name: 'requestedHeartbeat',
    type: 'int',
    isRequired: false,
    help: 'help',
    label: 'Requested heartbeat',
  },
  {
    name: 'exchangeName',
    type: 'string',
    isRequired: true,
    help: 'help',
    label: 'Exchange name',
  },
  {
    name: 'routingKey',
    type: 'string',
    isRequired: true,
    help: 'help',
    label: 'Routing key',
  },
];

export const rabbitMQDefault: RabbitMQConfigs = {
  connectionName: '',
  host: '',
  port: 5672,
  virtualHost: '',
  username: '',
  password: '',
  queueName: '',
  requestedChannelMax: 0,
  requestedFrameMax: 0,
  connectionTimeout: 60000,
  handshakeTimeout: 10000,
  requestedHeartbeat: 60,
  exchangeName: '',
  routingKey: '',
}