defaultPulsarImageTag: 2.11.0

tls:
  enabled: true
  proxy:
    enabled: true
  broker:
    enabled: true
  zookeeper:
    enabled: true

certs:
  internal_issuer:
    enabled: true
    type: selfsigning
