volumes:
  persistence: false

affinity:
  anti_affinity: false

components:
  autorecovery: false

## Monitoring Components
##
## Control what components of the monitoring stack to deploy for the cluster
monitoring:
  # monitoring - prometheus
  prometheus: true
  # monitoring - grafana
  grafana: true
  # monitoring - node_exporter
  node_exporter: false
  # alerting - alert-manager
  alert_manager: false

images:
  zookeeper:
    repository: apachepulsar/pulsar-all
    tag: 2.10.1
    pullPolicy: IfNotPresent
  bookie:
    repository: apachepulsar/pulsar-all
    tag: 2.10.1
    pullPolicy: IfNotPresent
  broker:
    repository: apachepulsar/pulsar-all
    tag: 2.10.1
    pullPolicy: IfNotPresent
  proxy:
    repository: apachepulsar/pulsar-all
    tag: 2.10.1
    pullPolicy: IfNotPresent
  functions:
    repository: apachepulsar/pulsar-all
    tag: 2.10.1

pulsar_metadata:
  component: pulsar-init
  image:
    # the image used for running `pulsar-cluster-initialize` job
    repository: apachepulsar/pulsar-all
    tag: 2.10.1

bookkeeper:
  replicaCount: 3
  securityContext:
    runAsUser: 0
    runAsGroup: 0

broker:
  replicaCount: 3
  configData:
    ## Enable `autoSkipNonRecoverableData` since bookkeeper is running
    ## without persistence
    autoSkipNonRecoverableData: "true"
    # Dev customizations
    brokerDeleteInactiveTopicsEnabled: "false"
  securityContext:
    runAsUser: 0
    runAsGroup: 0

  podSecurityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
    fsGroupChangePolicy: "OnRootMismatch"

proxy:
  replicaCount: 3
  ports:
    http: 8080 # Fix - https://github.com/apache/pulsar-helm-chart/issues/110
