port: 8090
publicBaseUrl: http://localhost:8090

library:
  path: /dekaf/library

pulsarInstance:
  name: default
  color: transparent
  brokerServiceUrl: "pulsar+ssl://cluster-d.o-xy6ek.snio.cloud:6651"
  webServiceUrl: "https://cluster-d.o-xy6ek.snio.cloud"
