version: '2.4'

services:
  pulsar:
    image: apachepulsar/pulsar-all:3.1.2
    command: /entrypoint.sh topic-level-policies-enabled
    restart: always
    environment:
      PULSAR_STANDALONE_USE_ZOOKEEPER: 1
    ports:
      - 6650:6650
      - 8080:8080
      - 2181:2181 # Zookeeper
    volumes:
      - $PWD/cases:/cases
      - $PWD/entrypoint.sh:/entrypoint.sh
      - pulsar-data:/pulsar/data

volumes:
  pulsar-data:

