version: '2.4'

services:
  grafana:
    image: pulsocat-grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - PULSAR_PROMETHEUS_URL=http://prometheus:9090
      - PULSAR_CLUSTER=${PULSAR_CLUSTER:-test2}
      - GRAFANA_DOMAIN=${GRAFANA_DOMAIN:-localhost:8090}
      - GRAFANA_ROOT_URL=http://${GRAFANA_DOMAIN}/grafana
      - GRAFANA_SERVE_FROM_SUB_PATH=true
    tty: true
    stdin_open: true
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./apache-pulsar-grafana-dashboard/prometheus/${PROMETHEUS_CONFIG_FILE:-standalone.yml.template}:/etc/prometheus/prometheus.yml
    restart: always