version: '2.4'

services:
  # pulsar:
  #   image: apachepulsar/pulsar:2.10.0
  #   command: /entrypoint.sh big-tree
  #   restart: always
  #   ports:
  #     - 6650:6650
  #     - 8080:8080
  #     - 2181:2181 # Zookeeper
  #   volumes:
  #     - $PWD/cases:/cases
  #     - $PWD/entrypoint.sh:/entrypoint.sh

  # # Pulsar Manager here is to compare it's behavior with our solution on same data.
  # pulsar-manager:
  #   image: apachepulsar/pulsar-manager:v0.3.0
  #   restart: always
  #   ports:
  #     - 9527:9527
  #     - 7750:7750
  #   environment:
  #     SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties
  #     USERNAME: pulsar
  #     PASSWORD: pulsar
  #   volumes:
  #     - $PWD/pulsar-manager/application.properties:/pulsar-manager/pulsar-manager/application.properties
  envoy:
    image: envoyproxy/envoy:v1.24-latest
    ports:
      - 10000:10000
      - 10001:10001
    volumes:
      - $PWD/envoy/envoy.yaml:/etc/envoy/envoy.yaml
