version: '2.4'

services:
  pulsar:
    image: apachepulsar/pulsar:2.10.2
    command: /entrypoint.sh topic-level-policies-enabled
    restart: always
    ports:
      - 6650:6650
      - 8080:8080
      - 2181:2181 # Zookeeper
    volumes:
      - $PWD/cases:/cases
      - $PWD/entrypoint.sh:/entrypoint.sh
