version: '2.4'

services:
  pulsar:
    image: apachepulsar/pulsar-all:2.11.0
    container_name: pulsar
    command: /entrypoint.sh topic-level-policies-enabled
    restart: always
    ports:
      - 6650:6650
      - 8080:8080
      - 2181:2181 # Zookeeper
    volumes:
      - $PWD/cases:/cases
      - $PWD/entrypoint.sh:/entrypoint.sh
      # - $PWD/pulsar/connectors/avro-schema.json:/pulsar/connectors/avro-schema.json
      # - $PWD/pulsar/connectors/pulsar-postgres-jdbc-sink.yaml:/pulsar/connectors/pulsar-postgres-jdbc-sink.yaml
  postgresql:
    image: postgres
    container_name: postgresdb
    restart: always
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  local_pgdata:
