export const help: Record<string, React.ReactElement> = {
  property: <div>Specific setting that controls some aspect of Pulsar's behavior.</div>,
  runtimeConfig: <div>Configurations that are set when you start a Pulsar instance.</div>,
  dynamicConfig: <div>Configurations that you can change while a Pulsar instance is running, without needing to restart the instance.</div>,
  acknowledgmentAtBatchIndexLevelEnabled: <div>Enable or disable the batch index acknowledgement.</div>,
  activeConsumerFailoverDelayTimeMillis: <div>How long to delay rewinding cursor and dispatching messages when active consumer is changed.</div>,
  additionalServletDirectory: <div>Location of broker additional servlet NAR directory</div>,
  additionalServlets: <div>Additional servlet name.<br /><br />If you have multiple additional servlets, separate them by commas.<br /><br />For example, additionalServlet_1, additionalServlet_2</div>,
  advertisedAddress: <div>The hostname or IP address that the standalone service advertises to the outside world. If not set, the value of <code>InetAddress.getLocalHost().getHostName()</code> is used.</div>,
  advertisedListeners: <div>
    Specify multiple advertised listeners for the broker.
    <br /><br />
    The format is <code>&lt;listener_name&gt;:pulsar://&lt;host&gt;:&lt;port&gt;</code>.
    <br /><br />
    If there are multiple listeners, separate them with commas.
    <br /><br />
    Note: do not use this configuration with <code>advertisedAddress</code> and <code>brokerServicePort</code>. If the value of this configuration is empty, the broker uses <code>advertisedAddress</code> and <code>brokerServicePort</code>
  </div>,
  aggregatePublisherStatsByProducerName: <div>If true, aggregate publisher stats of PartitionedTopicStats by producerName</div>,
  allowAutoSubscriptionCreation: <div>Allow automated creation of subscriptions if set to true (default value).</div>,
  allowAutoTopicCreation: <div>Allow automated creation of topics if set to true (default value).</div>,
  allowAutoTopicCreationType: <div>The type of topic that is allowed to be automatically created. (partitioned/non-partitioned)</div>,
  anonymousUserRole: <div>When this parameter is not empty, unauthenticated users perform as anonymousUserRole.</div>,
  authenticateOriginalAuthData: <div>If this flag is set then the broker authenticates the original Auth data else it just accepts the originalPrincipal and authorizes it (if required).</div>,
  authenticationEnabled: <div>Enable authentication.</div>,
  authenticationProviders: <div>Authentication provider name list, which is a list of class names</div>,
  authenticationRefreshCheckSeconds: <div>Interval of time for checking for expired authentication credentials.</div>,
  authorizationAllowWildcardsMatching: <div>Allow wildcard matching in authorization.<br /><br />Wildcard matching only applicable if wildcard-char: * presents at first or last position eg: .pulsar.service, pulsar.service.</div>,
  authorizationEnabled: <div>Enforce authorization.</div>,
  authorizationProvider: <div>Authorization provider fully qualified class-name.</div>,
  autoShrinkForConsumerPendingAcksMap: <div>Whether to enable the automatic shrink of pendingAcks map, the default is false, which means it is not enabled. When there are a large number of share or key share consumers in the cluster, it can be enabled to reduce the memory consumption caused by pendingAcks.</div>,
  autoSkipNonRecoverableData: <div>Skip reading non-recoverable/unreadable data-ledger under managed-ledger&apos;s list.<br /><br />It helps when data-ledgers gets corrupted at bookkeeper and managed-cursor is stuck at that ledger.</div>,
  backlogQuotaCheckEnabled: <div>Enable backlog quota check. Enforces actions on topic when the quota is reached.</div>,
  backlogQuotaCheckIntervalInSeconds: <div>How often to check for topics that have reached the quota. It only takes effects when <code>backlogQuotaCheckEnabled</code> is true</div>,
  backlogQuotaDefaultLimitBytes: <div>Default per-topic backlog quota limit by size, less than 0 means no limitation. default is -1. Increase it if you want to allow larger msg backlog.</div>,
  backlogQuotaDefaultLimitGB: <div>@deprecated - Use backlogQuotaDefaultLimitBytes instead.</div>,
  backlogQuotaDefaultLimitSecond: <div>Default per-topic backlog quota limit by time in second, less than 0 means no limitation. default is -1. Increase it if you want to allow larger msg backlog.</div>,
  backlogQuotaDefaultRetentionPolicy: <div>Default backlog quota retention policy. Default is producer_request_hold<br /><br />producer_request_hold Policy which holds producer&apos;s send request until the resource becomes available (or holding times out) producer_exception Policy which throws javax.jms.ResourceAllocationException to the producer consumer_backlog_eviction Policy which evicts the oldest message from the slowest consumer&apos;s backlog.</div>,
  bindAddress: <div>Hostname or IP address the service binds on.</div>,
  bindAddresses: <div>Used to specify additional bind addresses for the broker. The value must format as &lt;listener_name&gt;:&lt;scheme&gt;://&lt;host&gt;:&lt;port&gt;, multiple bind addresses should be separated with commas. Associates each bind address with an advertised listener and protocol handler. Note that the brokerServicePort, brokerServicePortTls, webServicePort, and webServicePortTls properties define additional bindings.</div>,
  bookkeeperClientAuthenticationParameters: <div>Parameters for bookkeeper auth plugin.</div>,
  bookkeeperClientAuthenticationParametersName: <div>BookKeeper auth plugin implementation specifics parameters name and values.</div>,
  bookkeeperClientAuthenticationPlugin: <div>Authentication plugin to use when connecting to bookies.</div>,
  bookkeeperClientEnforceMinNumRacksPerWriteQuorum: <div>Enforces rack-aware bookie selection policy to pick bookies from bookkeeperClientMinNumRacksPerWriteQuorum racks for a writeQuorum.<br /><br />If BK can&apos;t find bookie then it would throw BKNotEnoughBookiesException instead of picking random one.</div>,
  bookkeeperClientExposeStatsToPrometheus: <div>Whether expose managed ledger client stats to Prometheus.</div>,
  bookkeeperClientGetBookieInfoIntervalSeconds: <div>Set the interval to periodically check bookie info.</div>,
  bookkeeperClientGetBookieInfoRetryIntervalSeconds: <div>Set the interval to retry a failed bookie info lookup.</div>,
  bookkeeperClientHealthCheckEnabled: <div>Enable bookies health check.<br /><br />Bookies that have more than the configured number of failure within the interval will be quarantined for some time. During this period, new ledgers won&apos;t be created on these bookies</div>,
  bookkeeperClientHealthCheckErrorThresholdPerInterval: <div>Bookies health check error threshold per check interval.</div>,
  bookkeeperClientHealthCheckIntervalSeconds: <div>Bookies health check interval in seconds.</div>,
  bookkeeperClientHealthCheckQuarantineTimeInSeconds: <div>Bookie health check quarantined time in seconds.</div>,
  bookkeeperClientIsolationGroups: <div>Enable bookie isolation by specifying a list of bookie groups to choose from.<br /><br />Any bookie outside the specified groups will not be used by the broker.</div>,
  bookkeeperClientMinNumRacksPerWriteQuorum: <div>Minimum number of racks per write quorum.<br /><br />BK rack-aware bookie selection policy will try to get bookies from at least bookkeeperClientMinNumRacksPerWriteQuorum racks for a write quorum.</div>,
  bookkeeperClientNumWorkerThreads: <div>Number of BookKeeper client worker threads. Default is Runtime.getRuntime().availableProcessors().</div>,
  bookkeeperClientQuarantineRatio: <div>Bookie quarantine ratio to avoid all clients quarantine the high pressure bookie servers at the same time.</div>,
  bookkeeperClientRackawarePolicyEnabled: <div>Enable rack-aware bookie selection policy.<br /><br />BK will chose bookies from different racks when forming a new bookie ensemble</div>,
  bookkeeperClientRegionawarePolicyEnabled: <div>Enable region-aware bookie selection policy.<br /><br />BK will chose bookies from different regions and racks when forming a new bookie ensemble</div>,
  bookkeeperClientReorderReadSequenceEnabled: <div>Enable/disable reordering read sequence on reading entries.</div>,
  bookkeeperClientSecondaryIsolationGroups: <div>Enable bookie secondary-isolation group if bookkeeperClientIsolationGroups doesn&apos;t have enough bookie available.</div>,
  bookkeeperClientSpeculativeReadTimeoutInMillis: <div>Speculative reads are initiated if a read request doesn&apos;t complete within a certain time Using a value of 0, is disabling the speculative reads.</div>,
  bookkeeperClientThrottleValue: <div>Throttle value for bookkeeper client.</div>,
  bookkeeperClientTimeoutInSeconds: <div>Timeout for BK add / read operations.</div>,
  bookkeeperDiskWeightBasedPlacementEnabled: <div>Enable/disable disk weight based placement. Default is false.</div>,
  bookkeeperEnableStickyReads: <div>Enable/disable having read operations for a ledger to be sticky to a single bookie. If this flag is enabled, the client will use one single bookie (by preference) to read all entries for a ledger.</div>,
  bookkeeperExplicitLacIntervalInMills: <div>Set the interval to check the need for sending an explicit LAC.</div>,
  bookkeeperMetadataServiceUri: <div>Metadata service uri that bookkeeper is used for loading corresponding metadata driver and resolving its metadata service location.</div>,
  bookkeeperNumberOfChannelsPerBookie: <div>Number of channels per bookie.</div>,
  bookkeeperTlsCertFilesRefreshDurationSeconds: <div>Tls cert refresh duration at bookKeeper-client in seconds (0 to disable check).</div>,
  bookkeeperTLSCertificateFilePath: <div>Path for the TLS certificate file.</div>,
  bookkeeperTLSClientAuthentication: <div>Enable tls authentication with bookie.</div>,
  bookkeeperTLSKeyFilePath: <div>Path for the TLS private key file.</div>,
  bookkeeperTLSKeyFileType: <div>Supported type: PEM, JKS, PKCS12. Default value: PEM.</div>,
  bookkeeperTLSKeyStorePasswordPath: <div>Path to file containing keystore password, if the client keystore is password protected.</div>,
  bookkeeperTLSProviderFactoryClass: <div>Set the client security provider factory class name. Default: org.apache.bookkeeper.tls.TLSContextFactory</div>,
  bookkeeperTLSTrustCertsFilePath: <div>Path for the trusted TLS certificate file.</div>,
  bookkeeperTLSTrustCertTypes: <div>Supported type: PEM, JKS, PKCS12. Default value: PEM</div>,
  bookkeeperTLSTrustStorePasswordPath: <div>Path to file containing truststore password, if the client truststore is password protected.</div>,
  bookkeeperUseV2WireProtocol: <div>Use older Bookkeeper wire protocol with bookie.</div>,
  bootstrapNamespaces: <div>A comma-separated list of namespaces to bootstrap.</div>,
  brokerClientAuthenticationParameters: <div>Authentication parameters of the authentication plugin the broker is using to connect to other brokers.</div>,
  brokerClientAuthenticationPlugin: <div>Authentication settings of the broker itself.<br /><br />Used when the broker connects to other brokers, either in same or other clusters. Default uses plugin which disables authentication.</div>,
  brokerClientSslProvider: <div>The TLS Provider used by internal client to authenticate with other Pulsar brokers.</div>,
  brokerClientTlsCiphers: <div>Specify the tls cipher the internal client will use to negotiate during TLS Handshake (a comma-separated list of ciphers).<br /><br />Examples:- [TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256]. used by the internal client to authenticate with Pulsar brokers</div>,
  brokerClientTlsEnabled: <div>Enable TLS when talking with other brokers in the same cluster (admin operation) or different clusters (replication).</div>,
  brokerClientTlsEnabledWithKeyStore: <div>Whether internal client use KeyStore type to authenticate with other Pulsar brokers.</div>,
  brokerClientTlsProtocols: <div>Specify the tls protocols the broker will use to negotiate during TLS handshake (a comma-separated list of protocol names).<br /><br />Examples:- [TLSv1.3, TLSv1.2] used by the internal client to authenticate with Pulsar brokers.</div>,
  brokerClientTlsTrustStore: <div>TLS TrustStore path for internal client, used by the internal client to authenticate with Pulsar brokers.</div>,
  brokerClientTlsTrustStorePassword: <div>TLS TrustStore password for internal client, used by the internal client to authenticate with Pulsar brokers.</div>,
  brokerClientTlsTrustStoreType: <div>TLS TrustStore type configuration for internal client: JKS, PKCS12 used by the internal client to authenticate with Pulsar brokers.</div>,
  brokerClientTrustCertsFilePath: <div>TLS trusted certificate file for internal client, used by the internal client to authenticate with Pulsar brokers.</div>,
  brokerDeduplicationEnabled: <div>Set the default behavior for message deduplication in the broker.<br /><br />This can be overridden per-namespace. If enabled, broker will reject messages that were already stored in the topic.</div>,
  brokerDeduplicationEntriesInterval: <div>Number of entries after which a dedup info snapshot is taken.<br /><br />A bigger interval will lead to less snapshots being taken though it would increase the topic recovery time, when the entries published after the snapshot need to be replayed.</div>,
  brokerDeduplicationMaxNumberOfProducers: <div>Maximum number of producer information that it&apos;s going to be persisted for deduplication purposes.</div>,
  brokerDeduplicationProducerInactivityTimeoutMinutes: <div>Time of inactivity after which the broker will discard the deduplication information relative to a disconnected producer. Default is 6 hours.</div>,
  brokerDeduplicationSnapshotFrequencyInSeconds: <div>How often is the thread pool scheduled to check whether a snapshot needs to be taken.(disable with value 0).</div>,
  brokerDeduplicationSnapshotIntervalSeconds: <div>If this time interval is exceeded, a snapshot will be taken.It will run simultaneously with <code>brokerDeduplicationEntriesInterval</code></div>,
  brokerDeleteInactivePartitionedTopicMetadataEnabled: <div>Metadata of inactive partitioned topic will not be automatically cleaned up by default. Note: If <code>allowAutoTopicCreation</code> and this option are enabled at the same time, it may appear that a partitioned topic has just been deleted but is automatically created as a non-partitioned topic.</div>,
  brokerDeleteInactiveTopicsEnabled: <div>Enable the deletion of inactive topics. If only enable this option, will not clean the metadata of partitioned topic.</div>,
  brokerDeleteInactiveTopicsFrequencySeconds: <div>How often to check for inactive topics.</div>,
  brokerDeleteInactiveTopicsMaxInactiveDurationSeconds: <div>Max duration of topic inactivity in seconds, default is not present If not present, brokerDeleteInactiveTopicsFrequencySeconds will be used Topics that are inactive for longer than this value will be deleted.</div>,
  brokerDeleteInactiveTopicsMode: <div>Set the inactive topic delete mode. Default is delete_when_no_subscriptions delete_when_no_subscriptions mode only delete the topic which has no subscriptions and no active producers delete_when_subscriptions_caught_up mode only delete the topic that all subscriptions has no backlogs(caught up) and no active producers/consumers.</div>,
  brokerEntryMetadataInterceptors: <div>List of interceptors for entry metadata.</div>,
  brokerEntryPayloadProcessors: <div>List of interceptors for payload processing.</div>,
  brokerInterceptors: <div>List of broker interceptor to load, which is a list of broker interceptor names.</div>,
  brokerInterceptorsDirectory: <div>The directory to locate broker interceptors.</div>,
  brokerMaxConnections: <div>The maximum number of connections in the broker. If it exceeds, new connections are rejected.</div>,
  brokerMaxConnectionsPerIp: <div>The maximum number of connections per IP. If it exceeds, new connections are rejected.</div>,
  brokerPublisherThrottlingMaxByteRate: <div>Max Rate(in 1 seconds) of Byte allowed to publish for a broker when broker publish rate limiting enabled. (Disable byte rate limit with value 0).</div>,
  brokerPublisherThrottlingMaxMessageRate: <div>Max Rate(in 1 seconds) of Message allowed to publish for a broker when broker publish rate limiting enabled. (Disable message rate limit with value 0).</div>,
  brokerPublisherThrottlingTickTimeMillis: <div>Tick time to schedule task that checks broker publish rate limiting across all topics Reducing to lower value can give more accuracy while throttling publish but it uses more CPU to perform frequent check. (Disable publish throttling with value 0).</div>,
  brokerServiceCompactionMonitorIntervalInSeconds: <div>Interval between checks to see if topics with compaction policies need to be compacted.</div>,
  brokerServiceCompactionPhaseOneLoopTimeInSeconds: <div>Timeout for the compaction phase one loop, If the execution time of the compaction phase one loop exceeds this time, the compaction will not proceed.</div>,
  brokerServiceCompactionThresholdInBytes: <div>The estimated backlog size is greater than this threshold, compression will be triggered. Using a value of 0, is disabling compression check.</div>,
  brokerServicePort: <div>The port for serving binary protobuf requests. If set, defines a server binding for bindAddress:brokerServicePort. The Default value is 6650.</div>,
  brokerServicePortTls: <div>The port for serving TLS-secured binary protobuf requests. If set, defines a server binding for bindAddress:brokerServicePortTls.</div>,
  brokerServicePurgeInactiveFrequencyInSeconds: <div>How often broker checks for inactive topics to be deleted (topics with no subscriptions and no one connected) Deprecated in favor of using <code>brokerDeleteInactiveTopicsFrequencySeconds</code> @deprecated - unused.</div>,
  brokerShutdownTimeoutMs: <div>Time to wait for broker graceful shutdown. After this time elapses, the process will be killed.</div>,
  clientLibraryVersionCheckEnabled: <div>Enable check for minimum allowed client library version.</div>,
  clusterName: <div>Name of the cluster to which this broker belongs to.</div>,
  configurationMetadataStoreUrl: <div>The metadata store URL for the configuration data. If empty, we fall back to use metadataStoreUrl.</div>,
  configurationStoreServers: <div>Configuration store connection string (as a comma-separated list). Deprecated in favor of <code>configurationMetadataStoreUrl</code>.</div>,
  defaultNamespaceBundleSplitAlgorithm: <div>Default algorithm name for namespace bundle split.</div>,
  defaultNumberOfNamespaceBundles: <div>When a namespace is created without specifying the number of bundle, this value will be used as the default.</div>,
  defaultNumPartitions: <div>The number of partitioned topics that is allowed to be automatically createdif allowAutoTopicCreationType is partitioned.</div>,
  defaultRetentionSizeInMB: <div>Default retention size. 0 means retention is disabled. -1 means data is not removed by size quota.</div>,
  defaultRetentionTimeInMinutes: <div>Default message retention time. 0 means retention is disabled. -1 means data is not removed by time quota.</div>,
  delayedDeliveryEnabled: <div>Whether to enable the delayed delivery for messages.</div>,
  delayedDeliveryTickTimeMillis: <div>Control the tick time for when retrying on delayed delivery, affecting the accuracy of the delivery time compared to the scheduled time. Default is 1 second. Note that this time is used to configure the HashedWheelTimer&apos;s tick time for the InMemoryDelayedDeliveryTrackerFactory.</div>,
  delayedDeliveryTrackerFactoryClassName: <div>Class name of the factory that implements the delayed deliver tracker.</div>,
  disableBrokerInterceptors: <div>Enable or disable the broker interceptor, which is only used for testing for now.</div>,
  disableHttpDebugMethods: <div>If true, the broker will reject all HTTP requests using the TRACE and TRACK verbs. This setting may be necessary if the broker is deployed into an environment that uses http port scanning and flags web servers allowing the TRACE method as insecure.</div>,
  dispatcherMaxReadBatchSize: <div>Max number of entries to read from bookkeeper. By default it is 100 entries.</div>,
  dispatcherMaxReadSizeBytes: <div>Max size in bytes of entries to read from bookkeeper. By default it is 5MB.</div>,
  dispatcherMaxRoundRobinBatchSize: <div>Max number of entries to dispatch for a shared subscription. By default it is 20 entries.</div>,
  dispatcherMinReadBatchSize: <div>Min number of entries to read from bookkeeper. By default it is 1 entries.When there is an error occurred on reading entries from bookkeeper, the broker will backoff the batch size to this minimum number.</div>,
  dispatcherReadFailureBackoffInitialTimeInMs: <div>The read failure backoff initial time in milliseconds. By default it is 15s.</div>,
  dispatcherReadFailureBackoffMandatoryStopTimeInMs: <div>The read failure backoff mandatory stop time in milliseconds. By default it is 0s.</div>,
  dispatcherReadFailureBackoffMaxTimeInMs: <div>The read failure backoff max time in milliseconds. By default it is 60s.</div>,
  dispatchThrottlingOnBatchMessageEnabled: <div>Apply dispatch rate limiting on batch message instead individual messages with in batch message. (Default is disabled).</div>,
  dispatchThrottlingOnNonBacklogConsumerEnabled: <div>Default dispatch-throttling is disabled for consumers which already caught-up with published messages and don&apos;t have backlog. This enables dispatch-throttling for non-backlog consumers as well.</div>,
  dispatchThrottlingRateInByte: <div>Default bytes per second dispatch throttling-limit for whole broker. Using a value of 0, is disabling default message-byte dispatch-throttling.</div>,
  dispatchThrottlingRateInMsg: <div>Default messages per second dispatch throttling-limit for whole broker. Using a value of 0, is disabling default message-byte dispatch-throttling.</div>,
  dispatchThrottlingRatePerReplicatorInByte: <div>Default number of message-bytes dispatching throttling-limit for every replicator in replication.<br /><br />Using a value of 0, is disabling replication message-byte dispatch-throttling.</div>,
  dispatchThrottlingRatePerReplicatorInMsg: <div>Default number of message dispatching throttling-limit for every replicator in replication.<br /><br />Using a value of 0, is disabling replication message dispatch-throttling.</div>,
  dispatchThrottlingRatePerSubscriptionInByte: <div>Default number of message-bytes dispatching throttling-limit for a subscription.<br /><br />Using a value of 0, is disabling default message-byte dispatch-throttling.</div>,
  dispatchThrottlingRatePerSubscriptionInMsg: <div>Default number of message dispatching throttling-limit for a subscription.<br /><br />Using a value of 0, is disabling default message dispatch-throttling.</div>,
  dispatchThrottlingRatePerTopicInByte: <div>Default number of message-bytes dispatching throttling-limit for every topic.<br /><br />Using a value of 0, is disabling default message-byte dispatch-throttling.</div>,
  dispatchThrottlingRatePerTopicInMsg: <div>Default number of message dispatching throttling-limit for every topic.<br /><br />Using a value of 0, is disabling default message dispatch-throttling</div>,
  dispatchThrottlingRateRelativeToPublishRate: <div>Dispatch rate-limiting relative to publish rate. (Enabling flag will make broker to dynamically update dispatch-rate relatively to publish-rate: throttle-dispatch-rate = (publish-rate + configured dispatch-rate).</div>,
  enableBusyWait: <div>Option to enable busy-wait settings. Default is false. WARNING: This option will enable spin-waiting on executors and IO threads in order to reduce latency during context switches. The spinning will consume 100% CPU even when the broker is not doing any work. It is recommended to reduce the number of IO threads and BK client threads to only have few CPU cores busy.</div>,
  enableNamespaceIsolationUpdateOnTime: <div>Enable namespaceIsolation policy update take effect ontime or not, if set to ture, then the related namespaces will be unloaded after reset policy to make it take effect.</div>,
  enableNonPersistentTopics: <div>Enable broker to load non-persistent topics.</div>,
  enablePackagesManagement: <div>Enable the packages management service or not.</div>,
  enablePersistentTopics: <div>Enable broker to load persistent topics.</div>,
  enableReplicatedSubscriptions: <div>Enable tracking of replicated subscriptions state across clusters.</div>,
  enableRunBookieAutoRecoveryTogether: <div>Enable to run bookie autorecovery along with broker.</div>,
  enableRunBookieTogether: <div>Enable to run bookie along with broker.</div>,
  encryptionRequireOnProducer: <div>Enforce producer to publish encrypted messages.(default disable).</div>,
  entryFilterNames: <div>Class name of pluggable entry filter that decides whether the entry needs to be filtered.You can use this class to decide which entries can be sent to consumers.Multiple names need to be separated by commas.</div>,
  entryFiltersDirectory: <div>The directory for all the entry filter implementations.</div>,
  exposeBundlesMetricsInPrometheus: <div>Enable expose the broker bundles metrics.</div>,
  exposeConsumerLevelMetricsInPrometheus: <div>If true, export consumer level metrics otherwise namespace level.</div>,
  exposeManagedCursorMetricsInPrometheus: <div>If true, export managed cursor metrics.</div>,
  exposeManagedLedgerMetricsInPrometheus: <div>If true, export managed ledger metrics (aggregated by namespace).</div>,
  exposePreciseBacklogInPrometheus: <div>Enable expose the precise backlog stats. Set false to use published counter and consumed counter to calculate, this would be more efficient but may be inaccurate. Default is false.</div>,
  exposeProducerLevelMetricsInPrometheus: <div>If true, export producer level metrics otherwise namespace level.</div>,
  exposePublisherStats: <div>If true, export publisher stats when returning topics stats from the admin rest api.</div>,
  exposeSubscriptionBacklogSizeInPrometheus: <div>Enable expose the backlog size for each subscription when generating stats. Locking is used for fetching the status so default to false.</div>,
  exposeTopicLevelMetricsInPrometheus: <div>If true, export topic level metrics otherwise namespace level.</div>,
  exposingBrokerEntryMetadataToClientEnabled: <div>Enable or disable exposing broker entry metadata to client.</div>,
  failureDomainsEnabled: <div>Enable cluster&apos;s failure-domain which can distribute brokers into logical region.</div>,
  forceDeleteNamespaceAllowed: <div>Allow forced deletion of namespaces. Default is false.</div>,
  forceDeleteTenantAllowed: <div>Allow forced deletion of tenants. Default is false.</div>,
  functionsWorkerEnabled: <div>Flag indicates enabling or disabling function worker on brokers.</div>,
  functionsWorkerServiceNarPackage: <div>The nar package for the function worker service.</div>,
  globalZookeeperServers: <div>Global Zookeeper quorum connection string (as a comma-separated list). Deprecated in favor of using <code>configurationStoreServers</code></div>,
  haProxyProtocolEnabled: <div>Enable or disable the proxy protocol.</div>,
  httpMaxRequestSize: <div>If &gt; 0, it will reject all HTTP requests with bodies larged than the configured limit</div>,
  httpRequestsLimitEnabled: <div>Enable the enforcement of limits on the incoming HTTP requests.</div>,
  httpRequestsMaxPerSecond: <div>Max HTTP requests per seconds allowed. The excess of requests will be rejected with HTTP code 429 (Too many requests).</div>,
  internalListenerName: <div>Used to specify the internal listener name for the broker.The listener name must contain in the advertisedListeners.The Default value is absent, the broker uses the first listener as the internal listener.</div>,
  isAllowAutoUpdateSchemaEnabled: <div>Allow schema to be auto updated at broker level. User can override this by <code>is_allow_auto_update_schema</code> of namespace policy. This is enabled by default.</div>,
  isDelayedDeliveryDeliverAtTimeStrict: <div>When using the InMemoryDelayedDeliveryTrackerFactory (the default DelayedDeliverTrackerFactory), whether the deliverAt time is strictly followed. When false (default), messages may be sent to consumers before the deliverAt time by as much as the tickTimeMillis. This can reduce the overhead on the broker of maintaining the delayed index for a potentially very short time period. When true, messages will not be sent to consumer until the deliverAt time has passed, and they may be as late as the deliverAt time plus the tickTimeMillis for the topic plus the delayedDeliveryTickTimeMillis.</div>,
  isRunningStandalone: <div>Flag indicates whether to run broker in standalone mode.</div>,
  isSchemaValidationEnforced: <div>Enforce schema validation on following cases:<br /><br />- if a producer without a schema attempts to produce to a topic with schema, the producer will be failed to connect. PLEASE be carefully on using this, since non-java clients don&apos;t support schema. if you enable this setting, it will cause non-java clients failed to produce.</div>,
  jvmGCMetricsLoggerClassName: <div>Classname of Pluggable JVM GC metrics logger that can log GC specific metrics</div>,
  keepAliveIntervalSeconds: <div>How often to check pulsar connection is still alive.</div>,
  kinitCommand: <div>kerberos kinit command.</div>,
  lazyCursorRecovery: <div>Whether to recover cursors lazily when trying to recover a managed ledger backing a persistent topic. It can improve write availability of topics. The caveat is now when recovered ledger is ready to write we&apos;re not sure if all old consumers last mark delete position can be recovered or not.</div>,
  loadBalancerAutoBundleSplitEnabled: <div>Enable/disable automatic namespace bundle split.</div>,
  loadBalancerAutoUnloadSplitBundlesEnabled: <div>Enable/disable automatic unloading of split bundles.</div>,
  loadBalancerBandwithInResourceWeight: <div>BandwithIn Resource Usage Weight.</div>,
  loadBalancerBandwithOutResourceWeight: <div>BandwithOut Resource Usage Weight.</div>,
  loadBalancerBrokerComfortLoadLevelPercentage: <div>Usage threshold to determine a broker is having just right level of load (only used by <code>SimpleLoadManagerImpl</code>)</div>,
  loadBalancerBrokerMaxTopics: <div>Usage threshold to allocate max number of topics to broker.</div>,
  loadBalancerBrokerOverloadedThresholdPercentage: <div>Usage threshold to determine a broker as over-loaded.</div>,
  loadBalancerBrokerThresholdShedderPercentage: <div>Usage threshold to determine a broker whether to start threshold shedder.</div>,
  loadBalancerBrokerUnderloadedThresholdPercentage: <div>Usage threshold to determine a broker as under-loaded (only used by <code>SimpleLoadManagerImpl</code>)</div>,
  loadBalancerBundleUnloadMinThroughputThreshold: <div>Bundle unload minimum throughput threshold (MB).</div>,
  loadBalancerCPUResourceWeight: <div>CPU Resource Usage Weight.</div>,
  loadBalancerDirectMemoryResourceWeight: <div>Direct Memory Resource Usage Weight.</div>,
  loadBalancerEnabled: <div>Enable load balancer.</div>,
  loadBalancerHistoryResourcePercentage: <div>Resource history Usage Percentage When adding new resource usage info.</div>,
  loadBalancerHostUsageCheckIntervalMinutes: <div>Frequency of report to collect, in minutes.</div>,
  loadBalancerLoadSheddingStrategy: <div>load balance load shedding strategy (It requires broker restart if value is changed using dynamic config). Default is ThresholdShedder since 2.10.0.</div>,
  loadBalancerMemoryResourceWeight: <div>Memory Resource Usage Weight.</div>,
  loadBalancerMsgRateDifferenceShedderThreshold: <div>Message-rate percentage threshold between highest and least loaded brokers for uniform load shedding. (eg: broker1 with 50K msgRate and broker2 with 30K msgRate will have 66% msgRate difference and load balancer can unload bundles from broker-1 to broker-2).</div>,
  loadBalancerMsgThroughputMultiplierDifferenceShedderThreshold: <div>Message-throughput threshold between highest and least loaded brokers for uniform load shedding. (eg: broker1 with 450MB msgRate and broker2 with 100MB msgRate will have 4.5 times msgThroughout difference and load balancer can unload bundles from broker-1 to broker-2).</div>,
  loadBalancerNamespaceBundleMaxBandwidthMbytes: <div>Maximum bandwidth (in + out) in a bundle, otherwise bundle split will be triggered.</div>,
  loadBalancerNamespaceBundleMaxMsgRate: <div>Maximum msgRate (in + out) in a bundle, otherwise bundle split will be triggered.</div>,
  loadBalancerNamespaceBundleMaxSessions: <div>Maximum sessions (producers + consumers) in a bundle, otherwise bundle split will be triggered(disable threshold check with value -1).</div>,
  loadBalancerNamespaceBundleMaxTopics: <div>Maximum topics in a bundle, otherwise bundle split will be triggered.</div>,
  loadBalancerNamespaceMaximumBundles: <div>Maximum number of bundles in a namespace.</div>,
  loadBalancerOverrideBrokerNicSpeedGbps: <div>Option to override the auto-detected network interfaces max speed.</div>,
  loadBalancerPlacementStrategy: <div>load placement strategy[weightedRandomSelection/leastLoadedServer] (only used by <code>SimpleLoadManagerImpl</code>)</div>,
  loadBalancerReportUpdateMaxIntervalMinutes: <div>Maximum interval to update load report.</div>,
  loadBalancerReportUpdateThresholdPercentage: <div>Percentage of change to trigger load report update.</div>,
  loadBalancerResourceQuotaUpdateIntervalMinutes: <div>Interval to flush dynamic resource quota to ZooKeeper.</div>,
  loadBalancerSheddingEnabled: <div>Enable/disable automatic bundle unloading for load-shedding.</div>,
  loadBalancerSheddingGracePeriodMinutes: <div>Prevent the same topics to be shed and moved to other broker more than once within this timeframe.</div>,
  loadBalancerSheddingIntervalMinutes: <div>Load shedding interval.<br /><br />Broker periodically checks whether some traffic should be offload from some over-loaded broker to other under-loaded brokers.</div>,
  loadManagerClassName: <div>Name of load manager to use.</div>,
  managedCursorInfoCompressionType: <div>ManagedCursorInfo compression type, option values (NONE, LZ4, ZLIB, ZSTD, SNAPPY). If value is NONE, then save the ManagedCursorInfo bytes data directly.</div>,
  managedLedgerAddEntryTimeoutSeconds: <div>Add entry timeout when broker tries to publish message to bookkeeper.(0 to disable it).</div>,
  managedLedgerCacheCopyEntries: <div>Whether we should make a copy of the entry payloads when inserting in cache.</div>,
  managedLedgerCacheEvictionFrequency: <div>Configure the cache eviction frequency for the managed ledger cache.</div>,
  managedLedgerCacheEvictionTimeThresholdMillis: <div>All entries that have stayed in cache for more than the configured time, will be evicted.</div>,
  managedLedgerCacheEvictionWatermark: <div>Threshold to which bring down the cache level when eviction is triggered.</div>,
  managedLedgerCacheSizeMB: <div>Amount of memory to use for caching data payload in managed ledger.<br /><br />This memory is allocated from JVM direct memory and it&apos;s shared across all the topics running in the same broker. By default, uses 1/5th of available direct memory.</div>,
  managedLedgerCursorBackloggedThreshold: <div>Configure the threshold (in number of entries) from where a cursor should be considered backlogged and thus should be set as inactive.</div>,
  managedLedgerCursorMaxEntriesPerLedger: <div>Max number of entries to append to a cursor ledger.</div>,
  managedLedgerCursorPositionFlushSeconds: <div>How frequently to flush the cursor positions that were accumulated due to rate limiting. (seconds). Default is 60 seconds.</div>,
  managedLedgerCursorRolloverTimeInSeconds: <div>Max time before triggering a rollover on a cursor ledger.</div>,
  managedLedgerDataReadPriority: <div>Read priority when ledgers exists in both bookkeeper and the second layer storage.</div>,
  managedLedgerDefaultAckQuorum: <div>Number of guaranteed copies (acks to wait before write is complete).</div>,
  managedLedgerDefaultEnsembleSize: <div>Number of bookies to use when creating a ledger.</div>,
  managedLedgerDefaultMarkDeleteRateLimit: <div>Rate limit the amount of writes per second generated by consumer acking the messages.</div>,
  managedLedgerDefaultWriteQuorum: <div>Number of copies to store for each message.</div>,
  managedLedgerDigestType: <div>Default type of checksum to use when writing to BookKeeper. Default is <code>CRC32C</code>. Other possible options are <code>CRC32</code>, <code>MAC</code> or <code>DUMMY</code> (no checksum).</div>,
  managedLedgerInactiveLedgerRolloverTimeSeconds: <div>Time to rollover ledger for inactive topic (duration without any publish on that topic). Disable rollover with value 0 (Default value 0).</div>,
  managedLedgerInfoCompressionType: <div>ManagedLedgerInfo compression type, option values (NONE, LZ4, ZLIB, ZSTD, SNAPPY). If value is invalid or NONE, then save the ManagedLedgerInfo bytes data directly.</div>,
  managedLedgerMaxAckQuorum: <div>Max number of guaranteed copies (acks to wait before write is complete).</div>,
  managedLedgerMaxEnsembleSize: <div>Max number of bookies to use when creating a ledger.</div>,
  managedLedgerMaxEntriesPerLedger: <div>Max number of entries to append to a ledger before triggering a rollover.<br /><br />A ledger rollover is triggered after the min rollover time has passed and one of the following conditions is true: the max rollover time has been reached, the max entries have been written to the ledger, or the max ledger size has been written to the ledger.</div>,
  managedLedgerMaxLedgerRolloverTimeMinutes: <div>Maximum time before forcing a ledger rollover for a topic.</div>,
  managedLedgerMaxSizePerLedgerMbytes: <div>Maximum ledger size before triggering a rollover for a topic (MB).</div>,
  managedLedgerMaxUnackedRangesToPersist: <div>Max number of <code>acknowledgment holes</code> that are going to be persistently stored.<br /><br />When acknowledging out of order, a consumer will leave holes that are supposed to be quickly filled by acking all the messages. The information of which messages are acknowledged is persisted by compressing in <code>ranges</code> of messages that were acknowledged. After the max number of ranges is reached, the information will only be tracked in memory and messages will be redelivered in case of crashes.</div>,
  managedLedgerMaxUnackedRangesToPersistInZooKeeper: <div>Max number of acknowledgment holes that can be stored in Zookeeper.<br /><br />If number of unack message range is higher than this limit then broker will persist unacked ranges into bookkeeper to avoid additional data overhead into zookeeper. @deprecated - use managedLedgerMaxUnackedRangesToPersistInMetadataStore.</div>,
  managedLedgerMaxWriteQuorum: <div>Max number of copies to store for each message.</div>,
  managedLedgerMetadataOperationsTimeoutSeconds: <div>Operation timeout while updating managed-ledger metadata.</div>,
  managedLedgerMinLedgerRolloverTimeMinutes: <div>Minimum time between ledger rollover for a topic.</div>,
  managedLedgerNewEntriesCheckDelayInMillis: <div>New entries check delay for the cursor under the managed ledger. If no new messages in the topic, the cursor will try to check again after the delay time. For consumption latency sensitive scenario, can set to a smaller value or set to 0. Of course, this may degrade consumption throughput. Default is 10ms.</div>,
  managedLedgerNumSchedulerThreads: <div>Number of threads to be used for managed ledger scheduled tasks.</div>,
  managedLedgerNumWorkerThreads: <div> number of threads to be used for dispatching managed ledger tasks. Negative numbers are not allowed. If no value has been specified, the system will use the number of processors available to the Java virtual machine by default.</div>,
  managedLedgerOffloadAutoTriggerSizeThresholdBytes: <div>The number of bytes before triggering automatic offload to long term storage.</div>,
  managedLedgerOffloadDeletionLagMs: <div>Delay between a ledger being successfully offloaded to long term storage, and the ledger being deleted from bookkeeper.</div>,
  managedLedgerOffloadDriver: <div>Driver to use to offload old data to long term storage.</div>,
  managedLedgerOffloadMaxThreads: <div>Maximum number of thread pool threads for ledger offloading.</div>,
  managedLedgerOffloadPrefetchRounds: <div>Maximum prefetch rounds for ledger reading for offloading.</div>,
  managedLedgerPassword: <div>Default password to use when writing to BookKeeper.</div>,
  managedLedgerPrometheusStatsLatencyRolloverSeconds: <div>Managed ledger prometheus stats latency rollover seconds.</div>,
  managedLedgerReadEntryTimeoutSeconds: <div>Read entries timeout when broker tries to read messages from bookkeeper (0 to disable it).</div>,
  managedLedgerStatsPeriodSeconds: <div>How frequently to refresh the stats. (seconds). Default is 60 seconds.</div>,
  managedLedgerStorageClassName: <div>The class of the managed ledger storage.</div>,
  managedLedgerTraceTaskExecution: <div>Whether trace managed ledger task execution time.</div>,
  managedLedgerUnackedRangesOpenCacheSetEnabled: <div>Use Open Range-Set to cache unacked messages (it is memory efficient but it can take more cpu).</div>,
  maxConcurrentHttpRequests: <div>Max concurrent web requests.</div>,
  maxConcurrentLookupRequest: <div>Max number of concurrent lookup request broker allows to throttle heavy incoming lookup traffic.</div>,
  maxConcurrentNonPersistentMessagePerConnection: <div>Max concurrent non-persistent message can be processed per connection.</div>,
  maxConcurrentTopicLoadRequest: <div>Max number of concurrent topic loading request broker allows to control number of zk-operations.</div>,
  maxConsumerMetadataSize: <div>Maximum size of Consumer metadata.</div>,
  maxConsumersPerSubscription: <div>Max number of consumers allowed to connect to subscription.<br /><br />Once this limit reaches, Broker will reject new consumers until the number of connected consumers decrease. Using a value of 0, is disabling maxConsumersPerSubscription-limit check.</div>,
  maxConsumersPerTopic: <div>Max number of consumers allowed to connect to topic.<br /><br />Once this limit reaches, Broker will reject new consumers until the number of connected consumers decrease. Using a value of 0, is disabling maxConsumersPerTopic-limit check.</div>,
  maxMessagePublishBufferSizeInMB: <div>Max memory size for broker handling messages sending from producers.<br /><br />If the processing message size exceed this value, broker will stop read data from the connection. The processing messages means messages are sends to broker but broker have not send response to client, usually waiting to write to bookies.<br /><br />It&apos;s shared across all the topics running in the same broker.<br /><br />Use -1 to disable the memory limitation. Default is 1/2 of direct memory.</div>,
  maxMessageSize: <div>Max size of messages.</div>,
  maxNamespacesPerTenant: <div>The maximum number of namespaces that each tenant can create.This configuration is not precise control, in a concurrent scenario, the threshold will be exceeded.</div>,
  maxNumPartitionsPerPartitionedTopic: <div>The number of partitions per partitioned topic. If try to create or update partitioned topics by exceeded number of partitions, then fail.</div>,
  maxPendingPublishRequestsPerConnection: <div>Max pending publish requests per connection to avoid keeping large number of pending requests in memory. Default: 1000.</div>,
  maxProducersPerTopic: <div>Max number of producers allowed to connect to topic.<br /><br />Once this limit reaches, Broker will reject new producers until the number of connected producers decrease. Using a value of 0, is disabling maxProducersPerTopic-limit check.</div>,
  maxPublishRatePerTopicInBytes: <div>Max Rate(in 1 seconds) of Byte allowed to publish for a topic when topic publish rate limiting enabled. (Disable byte rate limit with value 0).</div>,
  maxPublishRatePerTopicInMessages: <div>Max Rate(in 1 seconds) of Message allowed to publish for a topic when topic publish rate limiting enabled. (Disable byte rate limit with value 0).</div>,
  maxSameAddressConsumersPerTopic: <div>Max number of consumers with the same IP address allowed to connect to topic.<br /><br />Once this limit reaches, Broker will reject new consumers until the number of connected consumers with the same IP address decrease. Using a value of 0, is disabling maxSameAddressConsumersPerTopic-limit check.</div>,
  maxSameAddressProducersPerTopic: <div>Max number of producers with the same IP address allowed to connect to topic.<br /><br />Once this limit reaches, Broker will reject new producers until the number of connected producers with the same IP address decrease. Using a value of 0, is disabling maxSameAddressProducersPerTopic-limit check.</div>,
  maxSubscriptionsPerTopic: <div>Max number of subscriptions allowed to subscribe to topic.<br /><br />Once this limit reaches, broker will reject new subscription until the number of subscribed subscriptions decrease. Using a value of 0, is disabling maxSubscriptionsPerTopic limit check.</div>,
  maxTenants: <div>The maximum number of tenants that each pulsar cluster can create.This configuration is not precise control, in a concurrent scenario, the threshold will be exceeded.</div>,
  maxTopicsPerNamespace: <div>Max number of topics allowed to be created in the namespace. When the topics reach the max topics of the namespace, the broker should reject the new topic request(include topic auto-created by the producer or consumer) until the number of connected consumers decrease. Using a value of 0, is disabling maxTopicsPerNamespace-limit check.</div>,
  maxUnackedMessagesPerBroker: <div>Max number of unacknowledged messages allowed per broker.<br /><br />Once this limit reaches, broker will stop dispatching messages to all shared subscription which has higher number of unack messages until subscriptions start acknowledging messages back and unack count reaches to <code>limit/2</code>. Using a value of 0, is disabling unackedMessage-limit check and broker doesn&apos;t block dispatchers.</div>,
  maxUnackedMessagesPerConsumer: <div>Max number of unacknowledged messages allowed to receive messages by a consumer on a shared subscription. Broker will stop sending messages to consumer once, this limit reaches until consumer starts acknowledging messages back and unack count reaches to <code>maxUnackedMessagesPerConsumer/2</code>. Using a value of 0, it is disabling unackedMessage-limit check and consumer can receive messages without any restriction.</div>,
  maxUnackedMessagesPerSubscription: <div>Max number of unacknowledged messages allowed per shared subscription. Broker will stop dispatching messages to all consumers of the subscription once this limit reaches until consumer starts acknowledging messages back and unack count reaches to limit/2. Using a value of 0, is disabling unackedMessage-limit check and dispatcher can dispatch messages without any restriction.</div>,
  maxUnackedMessagesPerSubscriptionOnBrokerBlocked: <div>Once broker reaches maxUnackedMessagesPerBroker limit, it blocks subscriptions which has higher unacked messages than this percentage limit and subscription will not receive any new messages until that subscription acks back <code>limit/2</code> messages.</div>,
  messageExpiryCheckIntervalInMinutes: <div>How frequently to proactively check and purge expired messages.</div>,
  messagePublishBufferCheckIntervalInMillis: <div>Interval between checks to see if message publish buffer size is exceed the max message publish buffer size.</div>,
  messagingProtocols: <div>List of messaging protocols to load, which is a list of protocol names.</div>,
  metadataStoreBatchingEnabled: <div>Whether we should enable metadata operations batching.</div>,
  metadataStoreBatchingMaxDelayMillis: <div>Maximum delay to impose on batching grouping.</div>,
  metadataStoreBatchingMaxOperations: <div>Maximum number of operations to include in a singular batch.</div>,
  metadataStoreBatchingMaxSizeKb: <div>Maximum size of a batch.</div>,
  metadataStoreCacheExpirySeconds: <div>Metadata store cache expiry time in seconds.</div>,
  metadataStoreConfigPath: <div>Configuration file path for local metadata store. It&apos;s supported by RocksdbMetadataStore for now.</div>,
  metadataStoreOperationTimeoutSeconds: <div>Metadata store operation timeout in seconds.</div>,
  metadataStoreSessionTimeoutMillis: <div>Metadata store session timeout in milliseconds.</div>,
  metadataStoreUrl: <div>The metadata store URL. Examples:<br /><br />zk:my-zk-1:2181,my-zk-2:2181,my-zk-3:2181<br />my-zk-1:2181,my-zk-2:2181,my-zk-3:2181 (will default to ZooKeeper when the schema is not specified)<br />zk:my-zk-1:2181,my-zk-2:2181,my-zk-3:2181/my-chroot-path (to add a ZK chroot path).</div>,
  metricsServletTimeoutMs: <div>Time in milliseconds that metrics endpoint would time out. Default is 30s. Increase it if there are a lot of topics to expose topic-level metrics. Set it to 0 to disable timeout.</div>,
  namespaceBundleUnloadingTimeoutMs: <div>Time to wait for the unloading of a namespace bundle.</div>,
  narExtractionDirectory: <div>The directory where nar Extraction of offloaders happens.</div>,
  numAcceptorThreads: <div>Number of threads to use for Netty Acceptor. Default is set to <code>1</code>.</div>,
  numCacheExecutorThreadPoolSize: <div>Number of thread pool size to use for pulsar zookeeper callback service.The cache executor thread pool is used for restarting global zookeeper session. Default is 10.</div>,
  numExecutorThreadPoolSize: <div>Number of threads to use for pulsar broker service. The executor in thread pool will do basic broker operation like load/unload bundle, update managedLedgerConfig, update topic/subscription/replicator message dispatch rate, do leader election etc. Default is set to 20.</div>,
  numHttpServerThreads: <div>Number of threads to use for HTTP requests processing Default is set to <code>2 * Runtime.getRuntime().availableProcessors()</code>.</div>,
  numIOThreads: <div>Number of threads to use for Netty IO. Default is set to <code>2 * Runtime.getRuntime().availableProcessors()</code>.</div>,
  numOrderedExecutorThreads: <div>Number of threads to use for orderedExecutor. The ordered executor is used to operate with zookeeper, such as init zookeeper client, get namespace policies from zookeeper etc. It also used to split bundle. Default is 8.</div>,
  numTransactionReplayThreadPoolSize: <div>Number of threads to use for pulsar transaction replay PendingAckStore or TransactionBuffer.Default is 5.</div>,
  numWorkerThreadsForNonPersistentTopic: <div>Number of worker threads to serve non-persistent topic.</div>,
  offloadersDirectory: <div>The directory to locate offloaders.</div>,
  packagesManagementLedgerRootPath: <div>The bookkeeper ledger root path.</div>,
  packagesManagementStorageProvider: <div>The packages management service storage service provider.</div>,
  packagesReplicas: <div>When the packages storage provider is bookkeeper, you can use this configuration to control the number of replicas for storing the package.</div>,
  preciseDispatcherFlowControl: <div>Precise dispatcher flow control according to history message number of each entry.</div>,
  preciseTimeBasedBacklogQuotaCheck: <div>Whether to enable precise time based backlog quota check. Enabling precise time based backlog quota check will cause broker to read first entry in backlog of the slowest cursor on a ledger which will mostly result in reading entry from BookKeeper’s disk which can have negative impact on overall performance. Disabling precise time based backlog quota check will just use the timestamp indicating when a ledger was closed, which is of coarser granularity.</div>,
  preciseTopicPublishRateLimiterEnable: <div>Enable precise rate limit for topic publish.</div>,
  preferLaterVersions: <div>If true, (and <code>ModularLoadManagerImpl</code> is being used), the load manager will attempt to use only brokers running the latest software version (to minimize impact to bundles).</div>,
  protocolHandlerDirectory: <div>The directory to locate messaging protocol handlers.</div>,
  proxyRoles: <div>Role names that are treated as <code>proxy roles</code>. If the broker sees a request with role as proxyRoles - it will demand to see the original client role or certificate.</div>,
  replicatedSubscriptionsSnapshotFrequencyMillis: <div>Frequency of snapshots for replicated subscriptions tracking.</div>,
  replicatedSubscriptionsSnapshotMaxCachedPerSubscription: <div>Max number of snapshot to be cached per subscription.</div>,
  replicatedSubscriptionsSnapshotTimeoutSeconds: <div>Timeout for building a consistent snapshot for tracking replicated subscriptions state.</div>,
  replicationConnectionsPerBroker: <div>Max number of connections to open for each broker in a remote cluster. More connections host-to-host lead to better throughput over high-latency links.</div>,
  replicationMetricsEnabled: <div>Enable replication metrics.</div>,
  replicationPolicyCheckDurationSeconds: <div>Duration to check replication policy to avoid replicator inconsistency due to missing ZooKeeper watch (disable with value 0).</div>,
  replicationProducerQueueSize: <div>Replicator producer queue size. When dynamically modified, it only takes effect for the newly added replicators.</div>,
  replicationTlsEnabled: <div>@deprecated - Use brokerClientTlsEnabled instead.</div>,
  replicatorPrefix: <div>Replicator prefix used for replicator producer name and cursor name.</div>,
  resourceUsageTransportClassName: <div>Default policy for publishing usage reports to system topic is disabled.This enables publishing of usage reports.</div>,
  resourceUsageTransportPublishIntervalInSecs: <div>Default interval to publish usage reports if <code>resourceUsagePublishToTopic</code> is enabled.</div>,
  retentionCheckIntervalInSeconds: <div>Check between intervals to see if consumed ledgers need to be trimmed.</div>,
  saslJaasClientAllowedIds: <div>This is a regexp, which limits the range of possible ids which can connect to the Broker using SASL. Default value is: “.pulsar.“, so only clients whose id contains &apos;pulsar&apos; are allowed to connect.</div>,
  saslJaasServerSectionName: <div>Service Principal, for login context name. Default value is “PulsarBroker”.</div>,
  schemaCompatibilityStrategy: <div>The schema compatibility strategy in broker level.</div>,
  schemaRegistryCompatibilityCheckers: <div>The list compatibility checkers to be used in schema registry.</div>,
  schemaRegistryStorageClassName: <div>The schema storage implementation used by this broker.</div>,
  skipBrokerShutdownOnOOM: <div>Flag to skip broker shutdown when broker handles Out of memory error.</div>,
  splitTopicAndPartitionLabelInPrometheus: <div>Enable splitting topic and partition label in Prometheus. If enabled, a topic name will split into 2 parts, one is topic name without partition index, another one is partition index, e.g. (topic=xxx, partition=0). If the topic is a non-partitioned topic, -1 will be used for the partition index. If disabled, one label to represent the topic and partition, e.g. (topic=xxx-partition-0) Default is false.</div>,
  statsUpdateFrequencyInSecs: <div>Stats update frequency in seconds.</div>,
  statsUpdateInitialDelayInSecs: <div>Stats update initial delay in seconds.</div>,
  statusFilePath: <div>Path for the file used to determine the rotation status for the broker when responding to service discovery health checks.</div>,
  streamingDispatch: <div>Whether to use streaming read dispatcher. Currently is in preview and can be changed in subsequent release.</div>,
  subscribeRatePeriodPerConsumerInSecond: <div>Rate period for <code>subscribeThrottlingRatePerConsumer</code>. Default is 30s.</div>,
  subscribeThrottlingRatePerConsumer: <div>Too many subscribe requests from a consumer can cause broker rewinding consumer cursors and loading data from bookies, hence causing high network bandwidth usage When the positive value is set, broker will throttle the subscribe requests for one consumer. Otherwise, the throttling will be disabled. The default value of this setting is 0 - throttling is disabled.</div>,
  subscriptionExpirationTimeMinutes: <div>How long to delete inactive subscriptions from last consuming. When it is 0, inactive subscriptions are not deleted automatically.</div>,
  subscriptionExpiryCheckIntervalInMinutes: <div>How frequently to proactively check and purge expired subscription.</div>,
  subscriptionKeySharedConsistentHashingReplicaPoints: <div>On KeyShared subscriptions, number of points in the consistent-hashing ring. The higher the number, the more equal the assignment of keys to consumers.</div>,
  subscriptionKeySharedEnable: <div>Enable Key_Shared subscription (default is enabled). @deprecated - use subscriptionTypesEnabled instead.</div>,
  subscriptionKeySharedUseConsistentHashing: <div>On KeyShared subscriptions, with default AUTO_SPLIT mode, use splitting ranges or consistent hashing to reassign keys to new consumers (default is consistent hashing).</div>,
  subscriptionRedeliveryTrackerEnabled: <div>Enable subscription message redelivery tracker to send redelivery count to consumer (default is enabled).</div>,
  subscriptionTypesEnabled: <div>Enable subscription types (default is all type enabled).</div>,
  superUserRoles: <div>Role names that are treated as <code>super-user</code>, meaning they will be able to do all admin operations and publish/consume from all topics.</div>,
  supportedNamespaceBundleSplitAlgorithms: <div>Supported algorithms name for namespace bundle split.</div>,
  systemTopicEnabled: <div>Enable or disable system topic.</div>,
  systemTopicSchemaCompatibilityStrategy: <div>The schema compatibility strategy to use for system topics.</div>,
  tlsAllowInsecureConnection: <div>Accept untrusted TLS certificate from client.</div>,
  tlsCertificateFilePath: <div>Path for the TLS certificate file.</div>,
  tlsCertRefreshCheckDurationSec: <div>Tls cert refresh duration in seconds (set 0 to check on every new connection).</div>,
  tlsCiphers: <div>Specify the tls cipher the broker will use to negotiate during TLS Handshake.<br /><br />Example:- [TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256]</div>,
  tlsEnabled: <div>Enable TLS.</div>,
  tlsEnabledWithKeyStore: <div>Enable TLS with KeyStore type configuration in broker.</div>,
  tlsKeyFilePath: <div>Path for the TLS private key file.</div>,
  tlsKeyStore: <div>TLS KeyStore path in broker.</div>,
  tlsKeyStorePassword: <div>TLS KeyStore password for broker.</div>,
  tlsKeyStoreType: <div>TLS KeyStore type configuration in broker: JKS, PKCS12.</div>,
  tlsProtocols: <div>Specify the tls protocols the broker will use to negotiate during TLS Handshake.<br /><br />Example:- [TLSv1.3, TLSv1.2]</div>,
  tlsProvider: <div>Specify the TLS provider for the broker service: When using TLS authentication with CACert, the valid value is either OPENSSL or JDK. When using TLS authentication with KeyStore, available values can be SunJSSE, Conscrypt and etc.</div>,
  tlsRequireTrustedClientCertOnConnect: <div>Specify whether Client certificates are required for TLS Reject. the Connection if the Client Certificate is not trusted.</div>,
  tlsTrustCertsFilePath: <div>Path for the trusted TLS certificate file.</div>,
  tlsTrustStore: <div>TLS TrustStore path in broker.</div>,
  tlsTrustStorePassword: <div>TLS TrustStore password for broker, null means empty password.</div>,
  tlsTrustStoreType: <div>TLS TrustStore type configuration in broker: JKS, PKCS12.</div>,
  topicFencingTimeoutSeconds: <div>If a topic remains fenced for this number of seconds, it will be closed forcefully. If it is set to 0 or a negative number, the fenced topic will not be closed.</div>,
  topicLevelPoliciesEnabled: <div>Enable or disable topic level policies, topic level policies depends on the system topic, please enable the system topic first.</div>,
  topicLoadTimeoutSeconds: <div>Amount of seconds to timeout when loading a topic. In situations with many geo-replicated clusters, this may need raised.</div>,
  topicPublisherThrottlingTickTimeMillis: <div>Tick time to schedule task that checks topic publish rate limiting across all topics Reducing to lower value can give more accuracy while throttling publish but it uses more CPU to perform frequent check. (Disable publish throttling with value 0).</div>,
  transactionBufferClientMaxConcurrentRequests: <div>The max concurrent requests for transaction buffer client.</div>,
  transactionBufferClientOperationTimeoutInMills: <div>The transaction buffer client&apos;s operation timeout in milliseconds.</div>,
  transactionBufferProviderClassName: <div>Class name for transaction buffer provider.</div>,
  transactionBufferSnapshotMaxTransactionCount: <div>Transaction buffer take snapshot transaction count.</div>,
  transactionBufferSnapshotMinTimeInMillis: <div>Transaction buffer take snapshot min interval time.</div>,
  transactionCoordinatorEnabled: <div>Enable transaction coordinator in broker.</div>,
  transactionMetadataStoreProviderClassName: <div>Class name for transaction metadata store provider.</div>,
  transactionPendingAckLogIndexMinLag: <div>MLPendingAckStore maintain a ConcurrentSkipListMap pendingAckLogIndex`,it store the position in pendingAckStore as value and save a position used to determinewhether the previous data can be cleaned up as a key.transactionPendingAckLogIndexMinLag is used to configure the minimum lag between indexes.</div>,
  transactionPendingAckStoreProviderClassName: <div>Class name for transaction pending ack store provider.</div>,
  ttlDurationDefaultInSeconds: <div>Default ttl for namespaces if ttl is not already configured at namespace policies. (disable default-ttl with value 0).</div>,
  unblockStuckSubscriptionEnabled: <div>Broker periodically checks if subscription is stuck and unblock if flag is enabled. (Default is disabled).</div>,
  useSeparateThreadPoolForProtocolHandlers: <div>Use a separate ThreadPool for each Protocol Handler.</div>,
  webServicePort: <div>The port for serving http requests.</div>,
  webServicePortTls: <div>The port for serving https requests.</div>,
  webServiceTlsCiphers: <div>Specify the tls cipher the proxy&apos;s web service will use to negotiate during TLS Handshake.<br /><br />Example:- [TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256].</div>,
  webServiceTlsProtocols: <div>Specify the tls protocols the proxy&apos;s web service will use to negotiate during TLS Handshake.<br /><br />Example:- [TLSv1.3, TLSv1.2].</div>,
  webServiceTlsProvider: <div>Specify the TLS provider for the web service: SunJSSE, Conscrypt and etc.</div>,
  webSocketConnectionsPerBroker: <div>Number of connections per Broker in Pulsar Client used in WebSocket proxy.</div>,
  webSocketMaxTextFrameSize: <div>The maximum size of a text message during parsing in WebSocket proxy.</div>,
  webSocketNumIoThreads: <div>Number of IO threads in Pulsar Client used in WebSocket proxy.</div>,
  webSocketServiceEnabled: <div>Enable the WebSocket API service in broker.</div>,
  webSocketSessionIdleTimeoutMillis: <div>Time in milliseconds that idle WebSocket session times out.</div>,
  zooKeeperCacheExpirySeconds: <div>ZooKeeper cache expiry time in seconds. @deprecated - Use metadataStoreCacheExpirySeconds instead.</div>,
  zooKeeperOperationTimeoutSeconds: <div>ZooKeeper operation timeout in seconds. @deprecated - Use metadataStoreOperationTimeoutSeconds instead.</div>,
  zookeeperServers: <div>The Zookeeper quorum connection string (as a comma-separated list). Deprecated in favour of <code>metadataStoreUrl</code>.</div>,
  zookeeperSessionExpiredPolicy: <div>There are two policies to apply when broker metadata session expires: session expired happens, “shutdown” or “reconnect”.<br /><br />With “shutdown”, the broker will be restarted.<br /><br />With “reconnect”, the broker will keep serving the topics, while attempting to recreate a new session.</div>,
  zooKeeperSessionTimeoutMillis: <div>ZooKeeper session timeout in milliseconds. @deprecated - Use metadataStoreSessionTimeoutMillis instead.</div>
}
