import { ReactNode } from "react";
import { ColumnKey } from "./Producers";

export const help: Record<ColumnKey, ReactNode> = {
  accessMode: "The type of access to the topic that the producer requires.",
  address: "IP address and source port for the connection of this producer.",
  averageMsgSize: "The average message size in bytes from this publisher within the last interval.",
  chunkedMessageRate: "The total rate of chunked messages published by this publisher.",
  clientVersion: "The client library version of this producer.",
  connectedSince: "The timestamp when this producer is created or reconnected last time.",
  isSupportsPartialProducer: "Whether partial producer is supported at client.",
  metadata: "The key-value metadata of this producer.",
  msgRateIn: "The total rate of messages (message per second) published by this publisher.",
  msgThroughputIn: "The total throughput (byte per second) of the messages published by this publisher.",
  producerId: "The internal identifier for this producer on this topic.",
  producerName: "The internal identifier for this producer, generated by the client library."
}
