type MicrosoftSqlConfigs = {
  "database.hostname": string,
  "database.port": number,
  "database.user": string,
  "database.password": string,
  "database.dbname": string,
  "database.server.name": string,
  "snapshot.mode": string,
  "topic.namespace": string,
  "task.class": string, //"io.debezium.connector.sqlserver.SqlServerConnectorTask",
  "value.converter": string, //"org.apache.kafka.connect.json.JsonConverter",
  "key.converter": string, //"org.apache.kafka.connect.json.JsonConverter",
  "typeClassName": string, //"org.apache.pulsar.common.schema.KeyValue",
  "database.history": string, //"org.apache.pulsar.io.debezium.PulsarDatabaseHistory",
  "database.tcpKeepAlive": boolean,
  "decimal.handling.mode": string,
  "database.history.pulsar.topic": string,
  "database.history.pulsar.service.url": string,
}

export const MicrosoftSqlDefault: MicrosoftSqlConfigs = {
  "database.hostname": '',
  "database.port": 1111,
  "database.user": '',
  "database.password": '',
  "database.dbname": '',
  "database.server.name": '',
  "snapshot.mode": '',
  "topic.namespace": '',
  "task.class": '', //"io.debezium.connector.sqlserver.SqlServerConnectorTask",
  "value.converter": '', //"org.apache.kafka.connect.json.JsonConverter",
  "key.converter": '', //"org.apache.kafka.connect.json.JsonConverter",
  "typeClassName": '', //"org.apache.pulsar.common.schema.KeyValue",
  "database.history": '', //"org.apache.pulsar.io.debezium.PulsarDatabaseHistory",
  "database.tcpKeepAlive": false,
  "decimal.handling.mode": '',
  "database.history.pulsar.topic": '',
  "database.history.pulsar.service.url": '',
}