import { IoConfigField } from "../../../../IoConfigField/IoConfigField"
import { dbNameField, dbServerNameField, hostnameField, passwordField, portField, pulsarHistoryServiceUrlField, userField } from "./debeziumConfigs"

export const debeziumOracleFields: IoConfigField[] = [
  hostnameField,
  portField,
  userField,
  passwordField,
  dbNameField,
  dbServerNameField,
  {
    name: 'schema.exclude.list',
    type: 'string',
    isRequired: true,
    help: 'help',
    label: 'Schema exclude list',
  },
  {
    name: 'snapshot.mode',
    type: 'string',
    isRequired: true,
    help: 'help',
    label: 'Snapshot mode',
  },
  {
    name: 'topic.namespace',
    type: 'string',
    isRequired: true,
    help: 'help',
    label: 'Namespace/topic',
  },
  {
    name: 'task.class',
    type: 'string',
    isRequired: true,
    help: 'help',
    label: 'Task class',
  },
  {
    name: 'value.converter',
    type: 'string',
    isRequired: true,
    help: 'help',
    label: 'Value converter',
  },
  {
    name: 'key.converter',
    type: 'string',
    isRequired: true,
    help: 'help',
    label: 'Key converter',
  },
  {
    name: 'typeClassName',
    type: 'string',
    isRequired: true,
    help: 'help',
    label: 'Type class name',
  },
  {
    name: 'database.history',
    type: 'string',
    isRequired: true,
    help: 'help',
    label: 'Database history',
  },
  {
    name: 'database.tcpKeepAlive',
    type: 'boolean',
    isRequired: true,
    help: 'help',
    label: 'TCP keep alive',
  },
  {
    name: 'decimal.handling.mode',
    type: 'string',
    isRequired: true,
    help: 'help',
    label: 'Decimal handling mode',
  },
  {
    name: 'database.history.pulsar.topic',
    type: 'string',
    isRequired: true,
    help: 'help',
    label: 'Pulsar database history',
  },
  pulsarHistoryServiceUrlField,
]

export type OracleConfigs = {
  [key: string]: string | number | boolean,
  "database.hostname": string,
  "database.port": number,
  "database.user": string,
  "database.password": string,
  "database.dbname": string,
  "database.server.name": string,
  "schema.exclude.list": string,
  "snapshot.mode": string,
  "topic.namespace": string, // "public/default",
  "task.class": string, //"io.debezium.connector.oracle.OracleConnectorTask",
  "value.converter": string, //"org.apache.kafka.connect.json.JsonConverter",
  "key.converter": string, //"org.apache.kafka.connect.json.JsonConverter",
  "typeClassName": string, //"org.apache.pulsar.common.schema.KeyValue",
  "database.history": string, //"org.apache.pulsar.io.debezium.PulsarDatabaseHistory",
  "database.tcpKeepAlive": boolean,
  "decimal.handling.mode": string,
  "database.history.pulsar.topic": string,
  "database.history.pulsar.service.url": string,
}

export const oracleDefault: OracleConfigs = {
  "database.hostname": '',
  "database.port": 1111,
  "database.user": '',
  "database.password": '',
  "database.dbname": '',
  "database.server.name": '',
  "schema.exclude.list": '',
  "snapshot.mode": '',
  "topic.namespace": '', // "public/default",
  "task.class": '', //"io.debezium.connector.oracle.OracleConnectorTask",
  "value.converter": '', //"org.apache.kafka.connect.json.JsonConverter",
  "key.converter": '', //"org.apache.kafka.connect.json.JsonConverter",
  "typeClassName": '', //"org.apache.pulsar.common.schema.KeyValue",
  "database.history": '', //"org.apache.pulsar.io.debezium.PulsarDatabaseHistory",
  "database.tcpKeepAlive": false,
  "decimal.handling.mode": '',
  "database.history.pulsar.topic": '',
  "database.history.pulsar.service.url": '',
}