import { IoConfigField } from "../../../../IoConfigField/IoConfigField";
import { StringMap } from "../../../../Sinks/configurationsFields/configurationsFields";

export const dynamoDbFields: IoConfigField[] = [
  {
    name: 'awsDynamodbStreamArn',
    type: 'string',
    isRequired: true,
    help: 'help',
    label: 'Stream arn',
  },
  {
    name: 'initialPositionInStream',
    type: 'string',
    isRequired: false,
    help: 'help',
    label: 'Initial position in stream',
  },
  {
    name: 'startAtTime',
    type: 'date',
    isRequired: false,
    help: 'help',
    label: 'Start at time',
  },
  {
    name: 'applicationName',
    type: 'string',
    isRequired: false,
    help: 'help',
    label: 'Application name',
  },
  {
    name: 'checkpointInterval',
    type: 'duration',
    isRequired: false,
    help: 'help',
    label: 'Checkpoint interval',
  },
  {
    name: 'backoffTime',
    type: 'duration',
    isRequired: false,
    help: 'help',
    label: 'Backoff time',
  },
  {
    name: 'numRetries',
    type: 'int',
    isRequired: false,
    help: 'help',
    label: '',
  },
  {
    name: 'receiveQueueSize',
    type: 'int',
    isRequired: false,
    help: 'help',
    label: 'Receive queue size',
  },
  {
    name: 'dynamoEndpoint',
    type: 'string',
    isRequired: false,
    help: 'help',
    label: 'Dynamo endpoint',
  },
  {
    name: 'cloudwatchEndpoint',
    type: 'string',
    isRequired: false,
    help: 'help',
    label: 'Cloud watch endpoint',
  },
  {
    name: 'awsEndpoint',
    type: 'string',
    isRequired: false,
    help: 'help',
    label: 'AWS endpoint',
  },
  {
    name: 'awsRegion',
    type: 'string',
    isRequired: false,
    help: 'help',
    label: 'AWS region',
  },
  {
    name: 'awsCredentialPluginName',
    type: 'string',
    isRequired: false,
    help: 'help',
    label: 'AWS credential plugin name',
  },
  {
    name: 'awsCredentialPluginParam',
    type: 'json',
    isRequired: false,
    help: 'help',
    label: 'AWS credential plugin param',
  },
];

export type DynamoDbConfigs = {
  [key: string]: string | number | boolean | Date | StringMap,
  awsDynamodbStreamArn: string,
  initialPositionInStream: string,
  startAtTime: Date,
  applicationName: string,
  checkpointInterval: number,
  backoffTim: number,
  numRetries: number,
  receiveQueueSize: number,
  dynamoEndpoint: string,
  cloudwatchEndpoint: string,
  awsEndpoint: string,
  awsRegion: string,
  awsCredentialPluginName: string,
  awsCredentialPluginParam: StringMap,
}

export const dynamoDbDefault: DynamoDbConfigs = {
  awsDynamodbStreamArn: '',
  initialPositionInStream: '',
  startAtTime: new Date(),
  applicationName: '',
  checkpointInterval: 0,
  backoffTim: 0,
  numRetries: 0,
  receiveQueueSize: 0,
  dynamoEndpoint: '',
  cloudwatchEndpoint: '',
  awsEndpoint: '',
  awsRegion: '',
  awsCredentialPluginName: '',
  awsCredentialPluginParam: {},
}