import { IoConfigField } from "../../../../IoConfigField/IoConfigField";

export const fileFields: IoConfigField[] = [
  {
    name: 'inputDirectory',
    type: 'string',
    isRequired: true,
    help: 'help',
    label: 'Input directory',
  },
  {
    name: 'recurse',
    type: 'boolean',
    isRequired: false,
    help: 'help',
    label: 'Recurse',
  },
  {
    name: 'keepFile',
    type: 'boolean',
    isRequired: false,
    help: 'help',
    label: 'Keep file',
  },
  {
    name: 'fileFilter',
    type: 'string',
    isRequired: false,
    help: 'help',
    label: 'File filter',
  },
  {
    name: 'pathFilter',
    type: 'string',
    isRequired: false,
    help: 'help',
    label: 'Path filter',
  },
  {
    name: 'minimumFileAge',
    type: 'int',
    isRequired: false,
    help: 'help',
    label: 'Minimum file age',
  },
  {
    name: 'maximumFileAge',
    type: 'int',
    isRequired: false,
    help: 'help',
    label: 'Maximum file age',
  },
  {
    name: 'minimumSize',
    type: 'int',
    isRequired: false,
    help: 'help',
    label: 'Minimum size',
  },
  {
    name: 'maximumSize',
    type: 'int',
    isRequired: false,
    help: 'help',
    label: 'Maximum size',
  },
  {
    name: 'ignoreHiddenFiles',
    type: 'boolean',
    isRequired: false,
    help: 'help',
    label: 'Ignore hidden files',
  },
  {
    name: 'pollingInterval',
    type: 'duration',
    isRequired: false,
    help: 'help',
    label: 'Polling interval',
  },
  {
    name: 'numWorkers',
    type: 'int',
    isRequired: false,
    help: 'help',
    label: 'Num workers',
  },
  {
    name: 'processedFileSuffix',
    type: 'string',
    isRequired: false,
    help: 'help',
    label: 'Processed file suffix',
  },
];

export type FileConfigs = {
  [key: string]: string | number | boolean,
  inputDirectory: string,
  recurse: boolean,
  keepFile: boolean,
  fileFilter: string,
  pathFilter: string,
  minimumFileAge: number,
  maximumFileAge: number,
  minimumSize: number,
  maximumSize: number,
  ignoreHiddenFiles: boolean,
  pollingInterval: number,
  numWorkers: number,
  processedFileSuffix: string,
}

export const fileDefault: FileConfigs = {
  inputDirectory: '',
  recurse: false,
  keepFile: false,
  fileFilter: '',
  pathFilter: '',
  minimumFileAge: 0,
  maximumFileAge: 0,
  minimumSize: 0,
  maximumSize: 0,
  ignoreHiddenFiles: false,
  pollingInterval: 0,
  numWorkers: 0,
  processedFileSuffix: '',
}