FROM tealtools/testrepo:buildimage as builder

WORKDIR /project

COPY . .

RUN cd /project/pulsar-ui && make build
# RUN cd /project/api-scala && make build

################################################################

FROM alpine:3.16.2

RUN apk --no-cache add ca-certificates
WORKDIR /app

USER tealuser

COPY --from=builder --chown=tealuser:tealuser /project/pulsar-ui/.next /app/ui/
RUN rm -rf /app/ui/.next/cache
