port: ${PULSOCAT_PORT}
publicUrl: ${PULSOCAT_PUBLIC_URL}

library:
  path: ${PULSOCAT_LIBRARY_PATH}

license:
  id: ${PULSOCAT_LICENSE_ID}
  token: ${PULSOCAT_LICENSE_TOKEN}

pulsarInstance:
  name: ${PULSOCAT_PULSAR_INSTANCE_NAME}
  color: transparent
  brokerServiceUrl: ${PULSOCAT_PULSAR_INSTANCE_BROKER_SERVICE_URL}
  webServiceUrl: ${PULSOCAT_PULSAR_INSTANCE_WEB_SERVICE_URL}
