port: 8095
publicUrl: ${PULSOCAT_PUBLIC_URL}

library:
  path: ${PULSOCAT_LIBRARY_PATH}

license:
  id: ${PULSOCAT_LICENSE_ID}
  token: ${PULSOCAT_LICENSE_TOKEN}
#
#pulsarInstance:
#  color: transparent
