defaultPulsarAuth: '{"type": "jwt", "token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik5rRXdSVVU1TUVOQlJrWTJNalEzTVRZek9FVkZRVVUyT0RNME5qUkRRVEU1T1VNMU16STVPUSJ9.eyJodHRwczovL3N0cmVhbW5hdGl2ZS5pby91c2VybmFtZSI6ImFkbWluQG8teHk2ZWsuYXV0aC5zdHJlYW1uYXRpdmUuY2xvdWQiLCJpc3MiOiJodHRwczovL2F1dGguc3RyZWFtbmF0aXZlLmNsb3VkLyIsInN1YiI6ImJuV09TNEk2eXZEb0hvdzRBY21NdlFqRVFHb080b0NZQGNsaWVudHMiLCJhdWQiOiJ1cm46c246cHVsc2FyOm8teHk2ZWs6aW5zdGFuY2UtZiIsImlhdCI6MTY5Mjg3Nzc4MSwiZXhwIjoxNjkzNDgyNTgxLCJhenAiOiJibldPUzRJNnl2RG9Ib3c0QWNtTXZRakVRR29PNG9DWSIsInNjb3BlIjoiYWRtaW4gYWNjZXNzIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIiwicGVybWlzc2lvbnMiOlsiYWRtaW4iLCJhY2Nlc3MiXX0.T4tYW1AwmEjU_2U2WKqNso71qDcrLhfqera46CypPr7iWzVM62oQDU69YauqpNHtJ9Dsf_TbjvGt1vv197G5tqklDLB4TZnKstCONZHiQDSu30m8i7_NPyaWNgi3qBLOzCl3MaOBx4afT1ms3iy_fy73bYpIUAQPsWiZwaFy2gTcOnqCsWUBWkt-OnW6sp3XqEJs-NjhMTc5XrCKW8f75rpkRHGMccCEU6OKLZTjTpyyW_-Z9KZjY_FWIgCflvsCcp5AV2mmsnAQWYfWlCxuh5PMcmOQ3KxjRl6bdczyOyT_CMsOETLro1k7mgYRWYUIFUESue4FSptAY1kuUsKOJA"}'

markdownsVariables:
  toolUrl: http://localhost:3000
  instance: metrics.streamnative.cloud:443
  proxyResourceName: grafana
  publicUrl: http://localhost:8090

instanceMarkdownPath: /ui/markdowns/instance.md
tenantMarkdownPath: /ui/markdowns/tenant.md
namespaceMarkdownPath: /ui/markdowns/namespace.md
topicMarkdownPath: /ui/markdowns/topic.md
