port: 8090
publicUrl: "http://localhost:8090"

library:
  path: "./library"

licenseKey: "activ-83e0efb7eefe60bf867079f555c574bav3"

pulsarInstance:
  name: "StreamNative instance-d"
#  color: "#ff0000"
#  brokerServiceUrl: "pulsar://localhost:6650"
  brokerServiceUrl: "pulsar+ssl://cluster-d.o-xy6ek.snio.cloud:6651"
#  webServiceUrl: "http://localhost:8080"
  webServiceUrl: "https://cluster-d.o-xy6ek.snio.cloud"
