proxies:
  - resource: grafana
    destination: http://localhost:3000
    headers:
      Authorization: Bearer glsa_e9RlLRPKMQAIsWKN80wrtlJ32CwuRm0L_66691009

markdownsVariables:
  toolUrl: http://localhost:3000
  instance: metrics.streamnative.cloud:443
  proxyResourceName: grafana
  publicUrl: http://localhost:8090

instanceMarkdownPath: /ui/markdowns/instance.md
tenantMarkdownPath: /ui/markdowns/tenant.md
namespaceMarkdownPath: /ui/markdowns/namespace.md
topicMarkdownPath: /ui/markdowns/topic.md
