port: 8090
publicUrl: "http://localhost:8090"

library:
  path: "./library"

pulsarInstance:
  name: "local"
  color: "#ff0000"
#  brokerServiceUrl: "pulsar://localhost:6650"
  brokerServiceUrl: "pulsar+ssl://test2.o-xy6ek.snio.cloud:6651"
#  webServiceUrl: "http://localhost:8080"
  webServiceUrl: "https://test2.o-xy6ek.snio.cloud"
