port: 8090
publicUrl: "http://localhost:8090"

library:
  path: "./library"

pulsarInstance:
  name: "local"
  color: "#ff0000"
  brokerServiceUrl: "pulsar+ssl://pulsar-devenv-proxy:6650"
  webServiceUrl: "https://pulsar-devenv-proxy:8080"

tls:
  tlsTrustCertsFilePath: "../devenv/helm/tmp/pulsar-proxy-ca.crt"
