port: 8090
publicUrl: "http://localhost:8090"

library:
  path: "./library"

pulsarInstance:
  name: "local"
  color: "#ff0000"
  brokerServiceUrl: "pulsar://localhost:6650"
  webServiceUrl: "http://localhost:8080"
