port: ${PULSOCAT_PORT}
publicUrl: ${PULSOCAT_PUBLIC_URL}

library:
  path: ${PULSOCAT_LIBRARY_PATH}

license:
  id: ${PULSOCAT_LICENSE_ID}
  token: ${PULSOCAT_LICENSE_TOKEN}

proxies:
  - name: grafana
    to: http://localhost:3000
    headers:
      - key: Authorization
        value: Bearer glsa_0FcgEIq7qKCaEXThkHjRIlI1FLhp0WXw_fbb43b52

resourcesInfoMarkdowns:
  vars:
    toolUrl: http://localhost:3000
    instanceUrl: metrics.streamnative.cloud:443
  instance: /ui/markdowns/instance.md
  tenant: /ui/markdowns/tenant.md
  namespace: /ui/markdowns/namespace.md
  topic: /ui/markdowns/topic.md

pulsarInstance:
  name: ${PULSOCAT_PULSAR_INSTANCE_NAME}
  color: transparent
  brokerServiceUrl: ${PULSOCAT_PULSAR_INSTANCE_BROKER_SERVICE_URL}
  webServiceUrl: ${PULSOCAT_PULSAR_INSTANCE_WEB_SERVICE_URL}
