port: 8090
publicUrl: "http://localhost:8090"

library:
  path: "./library"

license:
  id: "db1fa160-7f2f-4bdf-b3f2-5e194d2af2f6"
  token: "activ-44d2d91a3f7a41a0ff35d3d7936ffd8ev3"

pulsarInstance:
  name: "StreamNative instance-d"
#  color: "#ff0000"
#  brokerServiceUrl: "pulsar://localhost:6650"
  brokerServiceUrl: "pulsar+ssl://cluster-d.o-xy6ek.snio.cloud:6651"
#  webServiceUrl: "http://localhost:8080"
  webServiceUrl: "https://cluster-d.o-xy6ek.snio.cloud"
