// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.tools.teal.pulsar.ui.api.v1.consumer

sealed abstract class SubscriptionMode(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = SubscriptionMode
  def isSubscriptionModeUnspecified: _root_.scala.Boolean = false
  def isSubscriptionModeDurable: _root_.scala.Boolean = false
  def isSubscriptionModeNonDurable: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[SubscriptionMode] = com.tools.teal.pulsar.ui.api.v1.consumer.SubscriptionMode
  final def asRecognized: _root_.scala.Option[com.tools.teal.pulsar.ui.api.v1.consumer.SubscriptionMode.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[com.tools.teal.pulsar.ui.api.v1.consumer.SubscriptionMode.Recognized])
}

object SubscriptionMode extends _root_.scalapb.GeneratedEnumCompanion[SubscriptionMode] {
  sealed trait Recognized extends SubscriptionMode
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[SubscriptionMode] = this
  
  @SerialVersionUID(0L)
  case object SUBSCRIPTION_MODE_UNSPECIFIED extends SubscriptionMode(0) with SubscriptionMode.Recognized {
    val index = 0
    val name = "SUBSCRIPTION_MODE_UNSPECIFIED"
    override def isSubscriptionModeUnspecified: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object SUBSCRIPTION_MODE_DURABLE extends SubscriptionMode(1) with SubscriptionMode.Recognized {
    val index = 1
    val name = "SUBSCRIPTION_MODE_DURABLE"
    override def isSubscriptionModeDurable: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object SUBSCRIPTION_MODE_NON_DURABLE extends SubscriptionMode(2) with SubscriptionMode.Recognized {
    val index = 2
    val name = "SUBSCRIPTION_MODE_NON_DURABLE"
    override def isSubscriptionModeNonDurable: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends SubscriptionMode(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values = scala.collection.immutable.Seq(SUBSCRIPTION_MODE_UNSPECIFIED, SUBSCRIPTION_MODE_DURABLE, SUBSCRIPTION_MODE_NON_DURABLE)
  def fromValue(__value: _root_.scala.Int): SubscriptionMode = __value match {
    case 0 => SUBSCRIPTION_MODE_UNSPECIFIED
    case 1 => SUBSCRIPTION_MODE_DURABLE
    case 2 => SUBSCRIPTION_MODE_NON_DURABLE
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = ConsumerProto.javaDescriptor.getEnumTypes().get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = ConsumerProto.scalaDescriptor.enums(0)
}