package config

import zio.Config

case class AuthConfig(
    jwt: String
)

case class AppConfig(
    brokerServiceUrl: String,
    webServiceUrl: String,
    auth: AuthConfig,
    clusterNames: List[String]
)

val config = AppConfig(
  brokerServiceUrl = "pulsar+ssl://cluster-d.o-xy6ek.snio.cloud:6651",
  webServiceUrl = "https://cluster-d.o-xy6ek.snio.cloud",
  auth = AuthConfig(jwt = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik5rRXdSVVU1TUVOQlJrWTJNalEzTVRZek9FVkZRVVUyT0RNME5qUkRRVEU1T1VNMU16STVPUSJ9.eyJodHRwczovL3N0cmVhbW5hdGl2ZS5pby91c2VybmFtZSI6ImNsdXN0ZXItYi1hZG1pbkBvLXh5NmVrLmF1dGguc3RyZWFtbmF0aXZlLmNsb3VkIiwiaXNzIjoiaHR0cHM6Ly9hdXRoLnN0cmVhbW5hdGl2ZS5jbG91ZC8iLCJzdWIiOiJ6NUQxcVIyTllxN250amhZN0dHSnZqNkRrcG1PRk1EREBjbGllbnRzIiwiYXVkIjoidXJuOnNuOnB1bHNhcjpvLXh5NmVrOmluc3RhbmNlLWQiLCJpYXQiOjE2ODgxOTUwNjEsImV4cCI6MTY4ODc5OTg2MSwiYXpwIjoiejVEMXFSMk5ZcTdudGpoWTdHR0p2ajZEa3BtT0ZNREQiLCJzY29wZSI6ImFkbWluIGFjY2VzcyIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsInBlcm1pc3Npb25zIjpbImFkbWluIiwiYWNjZXNzIl19.UkXjwGzEFTDZ_k0fjIz_hDFwJLJ-i7dcAsjBJk-C3IZr10B0VXOJOCiMc4B1yshr_cB-YQmvUuRyrusWvTrTjcK-osjvNj8GKax2h4NNEfBRiGlcV-4hVfYlLguBt5WczA1ByEhEYlyQaFohHgMAYIidLyS5gXq3Wp-MsSLdSFPgCdnbATkx03ACwhD9e_zA8Vzbimy03LZX_Wyo_XVpZr_OjHtXMwk0YR87GZ2XK5L8HLcvrYqSwd93ybPvp5yl6M6sSUwMG-MA3wLlngnaLbJxA_MBM7o59l3F4WdswR8JRjadtqjvv_dMh0KPWPmwoHL1kH322cNPT5F2wuLmSw"),
  clusterNames = List("cluster-d")
)
