// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tools/teal/pulsar/ui/demoapp/schemas_tenant/v1/schemas_tenant.proto

package com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1;

public interface ProtobufNativeDemoMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double double = 1 [json_name = "double"];</code>
   * @return The double.
   */
  double getDouble();

  /**
   * <code>float float = 2 [json_name = "float"];</code>
   * @return The float.
   */
  float getFloat();

  /**
   * <code>int32 int32 = 3 [json_name = "int32"];</code>
   * @return The int32.
   */
  int getInt32();

  /**
   * <code>int64 int64 = 4 [json_name = "int64"];</code>
   * @return The int64.
   */
  long getInt64();

  /**
   * <code>uint32 uint32 = 5 [json_name = "uint32"];</code>
   * @return The uint32.
   */
  int getUint32();

  /**
   * <code>uint64 uint64 = 6 [json_name = "uint64"];</code>
   * @return The uint64.
   */
  long getUint64();

  /**
   * <code>sint32 sint32 = 7 [json_name = "sint32"];</code>
   * @return The sint32.
   */
  int getSint32();

  /**
   * <code>sint64 sint64 = 8 [json_name = "sint64"];</code>
   * @return The sint64.
   */
  long getSint64();

  /**
   * <code>fixed32 fixed32 = 9 [json_name = "fixed32"];</code>
   * @return The fixed32.
   */
  int getFixed32();

  /**
   * <code>fixed64 fixed64 = 10 [json_name = "fixed64"];</code>
   * @return The fixed64.
   */
  long getFixed64();

  /**
   * <code>sfixed32 sfixed32 = 11 [json_name = "sfixed32"];</code>
   * @return The sfixed32.
   */
  int getSfixed32();

  /**
   * <code>sfixed64 sfixed64 = 12 [json_name = "sfixed64"];</code>
   * @return The sfixed64.
   */
  long getSfixed64();

  /**
   * <code>bool bool = 13 [json_name = "bool"];</code>
   * @return The bool.
   */
  boolean getBool();

  /**
   * <code>string string = 14 [json_name = "string"];</code>
   * @return The string.
   */
  java.lang.String getString();
  /**
   * <code>string string = 14 [json_name = "string"];</code>
   * @return The bytes for string.
   */
  com.google.protobuf.ByteString
      getStringBytes();

  /**
   * <code>bytes bytes = 15 [json_name = "bytes"];</code>
   * @return The bytes.
   */
  com.google.protobuf.ByteString getBytes();

  /**
   * <code>.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.CoffeeEnum enum = 16 [json_name = "enum"];</code>
   * @return The enum numeric value on the wire for enum.
   */
  int getEnumValue();
  /**
   * <code>.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.CoffeeEnum enum = 16 [json_name = "enum"];</code>
   * @return The enum.
   */
  com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.CoffeeEnum getEnum();

  /**
   * <code>.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage nested_message = 17 [json_name = "nestedMessage"];</code>
   * @return Whether the nestedMessage field is set.
   */
  boolean hasNestedMessage();
  /**
   * <code>.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage nested_message = 17 [json_name = "nestedMessage"];</code>
   * @return The nestedMessage.
   */
  com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage getNestedMessage();
  /**
   * <code>.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessage nested_message = 17 [json_name = "nestedMessage"];</code>
   */
  com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.SimpleMessageOrBuilder getNestedMessageOrBuilder();

  /**
   * <code>map&lt;string, int64&gt; map = 18 [json_name = "map"];</code>
   */
  int getMapCount();
  /**
   * <code>map&lt;string, int64&gt; map = 18 [json_name = "map"];</code>
   */
  boolean containsMap(
      java.lang.String key);
  /**
   * Use {@link #getMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Long>
  getMap();
  /**
   * <code>map&lt;string, int64&gt; map = 18 [json_name = "map"];</code>
   */
  java.util.Map<java.lang.String, java.lang.Long>
  getMapMap();
  /**
   * <code>map&lt;string, int64&gt; map = 18 [json_name = "map"];</code>
   */

  long getMapOrDefault(
      java.lang.String key,
      long defaultValue);
  /**
   * <code>map&lt;string, int64&gt; map = 18 [json_name = "map"];</code>
   */

  long getMapOrThrow(
      java.lang.String key);

  /**
   * <code>repeated string repeated = 19 [json_name = "repeated"];</code>
   * @return A list containing the repeated.
   */
  java.util.List<java.lang.String>
      getRepeatedList();
  /**
   * <code>repeated string repeated = 19 [json_name = "repeated"];</code>
   * @return The count of repeated.
   */
  int getRepeatedCount();
  /**
   * <code>repeated string repeated = 19 [json_name = "repeated"];</code>
   * @param index The index of the element to return.
   * @return The repeated at the given index.
   */
  java.lang.String getRepeated(int index);
  /**
   * <code>repeated string repeated = 19 [json_name = "repeated"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the repeated at the given index.
   */
  com.google.protobuf.ByteString
      getRepeatedBytes(int index);

  /**
   * <code>string oneof_string = 100 [json_name = "oneofString"];</code>
   * @return Whether the oneofString field is set.
   */
  boolean hasOneofString();
  /**
   * <code>string oneof_string = 100 [json_name = "oneofString"];</code>
   * @return The oneofString.
   */
  java.lang.String getOneofString();
  /**
   * <code>string oneof_string = 100 [json_name = "oneofString"];</code>
   * @return The bytes for oneofString.
   */
  com.google.protobuf.ByteString
      getOneofStringBytes();

  /**
   * <code>int32 oneof_int32 = 101 [json_name = "oneofInt32"];</code>
   * @return Whether the oneofInt32 field is set.
   */
  boolean hasOneofInt32();
  /**
   * <code>int32 oneof_int32 = 101 [json_name = "oneofInt32"];</code>
   * @return The oneofInt32.
   */
  int getOneofInt32();

  /**
   * <code>bool oneof_bool = 102 [json_name = "oneofBool"];</code>
   * @return Whether the oneofBool field is set.
   */
  boolean hasOneofBool();
  /**
   * <code>bool oneof_bool = 102 [json_name = "oneofBool"];</code>
   * @return The oneofBool.
   */
  boolean getOneofBool();

  public com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1.ProtobufNativeDemoMessage.OneofCase getOneofCase();
}
