// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tools/teal/pulsar/ui/demoapp/schemas_tenant/v1/schemas_tenant.proto

package com.tools.teal.pulsar.ui.demoapp.schemas_tenant.v1;

public final class SchemasTenantProto {
  private SchemasTenantProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tools_teal_pulsar_ui_demoapp_schemas_tenant_v1_SimpleMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tools_teal_pulsar_ui_demoapp_schemas_tenant_v1_SimpleMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tools_teal_pulsar_ui_demoapp_schemas_tenant_v1_ProtobufNativeDemoMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tools_teal_pulsar_ui_demoapp_schemas_tenant_v1_ProtobufNativeDemoMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tools_teal_pulsar_ui_demoapp_schemas_tenant_v1_ProtobufNativeDemoMessage_MapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tools_teal_pulsar_ui_demoapp_schemas_tenant_v1_ProtobufNativeDemoMessage_MapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nCtools/teal/pulsar/ui/demoapp/schemas_t" +
      "enant/v1/schemas_tenant.proto\022.tools.tea" +
      "l.pulsar.ui.demoapp.schemas_tenant.v1\"+\n" +
      "\rSimpleMessage\022\014\n\001x\030\001 \001(\005R\001x\022\014\n\001y\030\002 \001(\005R" +
      "\001y\"\345\006\n\031ProtobufNativeDemoMessage\022\026\n\006doub" +
      "le\030\001 \001(\001R\006double\022\024\n\005float\030\002 \001(\002R\005float\022\024" +
      "\n\005int32\030\003 \001(\005R\005int32\022\024\n\005int64\030\004 \001(\003R\005int" +
      "64\022\026\n\006uint32\030\005 \001(\rR\006uint32\022\026\n\006uint64\030\006 \001" +
      "(\004R\006uint64\022\026\n\006sint32\030\007 \001(\021R\006sint32\022\026\n\006si" +
      "nt64\030\010 \001(\022R\006sint64\022\030\n\007fixed32\030\t \001(\007R\007fix" +
      "ed32\022\030\n\007fixed64\030\n \001(\006R\007fixed64\022\032\n\010sfixed" +
      "32\030\013 \001(\017R\010sfixed32\022\032\n\010sfixed64\030\014 \001(\020R\010sf" +
      "ixed64\022\022\n\004bool\030\r \001(\010R\004bool\022\026\n\006string\030\016 \001" +
      "(\tR\006string\022\024\n\005bytes\030\017 \001(\014R\005bytes\022N\n\004enum" +
      "\030\020 \001(\0162:.tools.teal.pulsar.ui.demoapp.sc" +
      "hemas_tenant.v1.CoffeeEnumR\004enum\022d\n\016nest" +
      "ed_message\030\021 \001(\0132=.tools.teal.pulsar.ui." +
      "demoapp.schemas_tenant.v1.SimpleMessageR" +
      "\rnestedMessage\022d\n\003map\030\022 \003(\0132R.tools.teal" +
      ".pulsar.ui.demoapp.schemas_tenant.v1.Pro" +
      "tobufNativeDemoMessage.MapEntryR\003map\022\032\n\010" +
      "repeated\030\023 \003(\tR\010repeated\022#\n\014oneof_string" +
      "\030d \001(\tH\000R\013oneofString\022!\n\013oneof_int32\030e \001" +
      "(\005H\000R\noneofInt32\022\037\n\noneof_bool\030f \001(\010H\000R\t" +
      "oneofBool\0326\n\010MapEntry\022\020\n\003key\030\001 \001(\tR\003key\022" +
      "\024\n\005value\030\002 \001(\003R\005value:\0028\001B\007\n\005oneof*\256\001\n\nC" +
      "offeeEnum\022\033\n\027COFFEE_ENUM_UNSPECIFIED\020\000\022\030" +
      "\n\024COFFEE_ENUM_ESPRESSO\020\001\022\031\n\025COFFEE_ENUM_" +
      "AMERICANO\020\002\022\032\n\026COFFEE_ENUM_CAPPUCCINO\020\003\022" +
      "\026\n\022COFFEE_ENUM_FRAPPE\020\004\022\032\n\026COFFEE_ENUM_F" +
      "LAT_WHITE\020\005B\245\002\n2com.tools.teal.pulsar.ui" +
      ".demoapp.schemas_tenant.v1B\022SchemasTenan" +
      "tProtoP\001\242\002\006TTPUDS\252\002-Tools.Teal.Pulsar.Ui" +
      ".Demoapp.SchemasTenant.V1\312\002-Tools\\Teal\\P" +
      "ulsar\\Ui\\Demoapp\\SchemasTenant\\V1\342\0029Tool" +
      "s\\Teal\\Pulsar\\Ui\\Demoapp\\SchemasTenant\\V" +
      "1\\GPBMetadata\352\0023Tools::Teal::Pulsar::Ui:" +
      ":Demoapp::SchemasTenant::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tools_teal_pulsar_ui_demoapp_schemas_tenant_v1_SimpleMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tools_teal_pulsar_ui_demoapp_schemas_tenant_v1_SimpleMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tools_teal_pulsar_ui_demoapp_schemas_tenant_v1_SimpleMessage_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_tools_teal_pulsar_ui_demoapp_schemas_tenant_v1_ProtobufNativeDemoMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tools_teal_pulsar_ui_demoapp_schemas_tenant_v1_ProtobufNativeDemoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tools_teal_pulsar_ui_demoapp_schemas_tenant_v1_ProtobufNativeDemoMessage_descriptor,
        new java.lang.String[] { "Double", "Float", "Int32", "Int64", "Uint32", "Uint64", "Sint32", "Sint64", "Fixed32", "Fixed64", "Sfixed32", "Sfixed64", "Bool", "String", "Bytes", "Enum", "NestedMessage", "Map", "Repeated", "OneofString", "OneofInt32", "OneofBool", "Oneof", });
    internal_static_tools_teal_pulsar_ui_demoapp_schemas_tenant_v1_ProtobufNativeDemoMessage_MapEntry_descriptor =
      internal_static_tools_teal_pulsar_ui_demoapp_schemas_tenant_v1_ProtobufNativeDemoMessage_descriptor.getNestedTypes().get(0);
    internal_static_tools_teal_pulsar_ui_demoapp_schemas_tenant_v1_ProtobufNativeDemoMessage_MapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tools_teal_pulsar_ui_demoapp_schemas_tenant_v1_ProtobufNativeDemoMessage_MapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
