nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []

pulsocat:
  config: |
    port: 8090
    publicUrl: ""

    library:
      path: "./library"

    license:
      id: ${PULSOCAT_LICENSE_ID}
      token: ${PULSOCAT_LICENSE_TOKEN}

    pulsarInstance:
      name: "default"
      color: "transparent"
      brokerServiceUrl: ""
      webServiceUrl: ""

  env: []

  image:
    repository: tealtools/pulsocat
    pullPolicy: IfNotPresent
    tag: "latest"

  nodeSelector: {}
  tolerations: []
  affinity: {}

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}

  resources:
    limits:
      cpu: 2000m
      memory: 4096Mi
    requests:
      cpu: 1000m
      memory: 2048Mi

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
