// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.google.rpc.code

object CodeProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """ChVnb29nbGUvcnBjL2NvZGUucHJvdG8SCmdvb2dsZS5ycGMq+QQKBENvZGUSDwoCT0sQABoH4j8EEgJPSxIdCglDQU5DRUxMR
  UQQARoO4j8LEglDQU5DRUxMRUQSGQoHVU5LTk9XThACGgziPwkSB1VOS05PV04SKwoQSU5WQUxJRF9BUkdVTUVOVBADGhXiPxISE
  ElOVkFMSURfQVJHVU1FTlQSLQoRREVBRExJTkVfRVhDRUVERUQQBBoW4j8TEhFERUFETElORV9FWENFRURFRBIdCglOT1RfRk9VT
  kQQBRoO4j8LEglOT1RfRk9VTkQSJwoOQUxSRUFEWV9FWElTVFMQBhoT4j8QEg5BTFJFQURZX0VYSVNUUxItChFQRVJNSVNTSU9OX
  0RFTklFRBAHGhbiPxMSEVBFUk1JU1NJT05fREVOSUVEEikKD1VOQVVUSEVOVElDQVRFRBAQGhTiPxESD1VOQVVUSEVOVElDQVRFR
  BIvChJSRVNPVVJDRV9FWEhBVVNURUQQCBoX4j8UEhJSRVNPVVJDRV9FWEhBVVNURUQSMQoTRkFJTEVEX1BSRUNPTkRJVElPThAJG
  hjiPxUSE0ZBSUxFRF9QUkVDT05ESVRJT04SGQoHQUJPUlRFRBAKGgziPwkSB0FCT1JURUQSIwoMT1VUX09GX1JBTkdFEAsaEeI/D
  hIMT1VUX09GX1JBTkdFEiUKDVVOSU1QTEVNRU5URUQQDBoS4j8PEg1VTklNUExFTUVOVEVEEhsKCElOVEVSTkFMEA0aDeI/ChIIS
  U5URVJOQUwSIQoLVU5BVkFJTEFCTEUQDhoQ4j8NEgtVTkFWQUlMQUJMRRIdCglEQVRBX0xPU1MQDxoO4j8LEglEQVRBX0xPU1NCm
  QEKDmNvbS5nb29nbGUucnBjQglDb2RlUHJvdG9QAVozZ29vZ2xlLmdvbGFuZy5vcmcvZ2VucHJvdG8vZ29vZ2xlYXBpcy9ycGMvY
  29kZTtjb2RlogIDR1JYqgIKR29vZ2xlLlJwY8oCCkdvb2dsZVxScGPiAhZHb29nbGVcUnBjXEdQQk1ldGFkYXRh6gILR29vZ2xlO
  jpScGNiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}