apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  serviceMonitorSelector: {}
  additionalScrapeConfigs:
    name: prometheus-scrape-configs
    key: prometheus-scrape-configs.yaml
