// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tools/teal/pulsar/ui/test/delivery_app/v1/delivery_app.proto

package com.tools.teal.pulsar.ui.test.delivery_app.v1;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tools.teal.pulsar.ui.test.delivery_app.v1.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2 [json_name = "age"];</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>repeated string hobbies = 3 [json_name = "hobbies"];</code>
   * @return A list containing the hobbies.
   */
  java.util.List<java.lang.String>
      getHobbiesList();
  /**
   * <code>repeated string hobbies = 3 [json_name = "hobbies"];</code>
   * @return The count of hobbies.
   */
  int getHobbiesCount();
  /**
   * <code>repeated string hobbies = 3 [json_name = "hobbies"];</code>
   * @param index The index of the element to return.
   * @return The hobbies at the given index.
   */
  java.lang.String getHobbies(int index);
  /**
   * <code>repeated string hobbies = 3 [json_name = "hobbies"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the hobbies at the given index.
   */
  com.google.protobuf.ByteString
      getHobbiesBytes(int index);
}
