on:
  - push

jobs:
  build-app:
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest

    runs-on: ${{matrix.runs-on}}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Installing Nix
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      # - name: Build and test app
      #   run: |
      #     nix build -L
      #     nix-shell --run 'make build-app'

      - name: Build Docker images
        uses: docker/setup-buildx-action@v1
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
        run: |
          nix-shell --run 'make build-docker-images'
