on:
  - push

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          # - macos-latest
        include:
          - os: ubuntu-20.04
            system: x86_64-linux
            experimental: false
          # - os: macos-latest
          #   system: x86_64-darwin
          #   experimental: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Installing Nix
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build and test
        run: |
          nix build -L
          nix-shell --run 'make build-jar'
