on:
  - push

jobs:
  build:
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest

    runs-on: ${{matrix.runs-on}}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Installing Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Use cache
        id: cache-all
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/share/containers/
            /nix/store
          key: cache-all

      # - name: Build and test app
      #   run: |
      #     nix build -L
      #     nix-shell --run 'make build-app'

      # - name: Setting up debug session using SSH
      #   uses: lhotari/action-upterm@v1

      - name: Build Docker images
        run: |
          nix-shell --run 'make build-docker-images'
