name: "Cleanup Runners"
on:
  schedule:
  - cron: "0 4 * * *"

jobs:
  cleanup:
    runs-on: [self-hosted, x64]
    steps:
      - run: nix-collect-garbage -d && docker system prune -a -f --volumes && df -h
